
RAID = [
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴍᴀᴅᴀʀᴄʜᴏᴅ ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ɢʜᴜᴛᴋᴀ ᴋʜᴀᴀᴋᴇ ᴛʜᴏᴏᴋ ᴅᴜɴɢᴀ 🤣🤣",
"ᴛᴇʀᴇ ʙᴇʜᴇɴ ᴋ ᴄʜᴜᴛ ᴍᴇ ᴄʜᴀᴋᴜ ᴅᴀᴀʟ ᴋᴀʀ ᴄʜᴜᴛ ᴋᴀ ᴋʜᴏᴏɴ ᴋᴀʀ ᴅᴜɢᴀ",
"ᴛᴇʀɪ ᴠᴀʜᴇᴇɴ ɴʜɪ ʜᴀɪ ᴋʏᴀ? 9 ᴍᴀʜɪɴᴇ ʀᴜᴋ ꜱᴀɢɪ ᴠᴀʜᴇᴇɴ ᴅᴇᴛᴀ ʜᴜ 🤣🤣🤩",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋ ʙʜᴏꜱᴅᴇ ᴍᴇ ᴀᴇʀᴏᴘʟᴀɴᴇᴘᴀʀᴋ ᴋᴀʀᴋᴇ ᴜᴅᴀᴀɴ ʙʜᴀʀ ᴅᴜɢᴀ ✈️🛫",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ꜱᴜᴛʟɪ ʙᴏᴍʙ ꜰᴏᴅ ᴅᴜɴɢᴀ ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴊʜᴀᴀᴛᴇ ᴊᴀʟ ᴋᴇ ᴋʜᴀᴀᴋ ʜᴏ ᴊᴀʏᴇɢɪ💣",
"ᴛᴇʀɪ ᴍᴀᴀᴋɪ ᴄʜᴜᴛ ᴍᴇ ꜱᴄᴏᴏᴛᴇʀ ᴅᴀᴀʟ ᴅᴜɢᴀ👅",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀᴇ ʙᴇʜᴇɴ ᴋ ᴄʜᴜᴛ ᴍᴇ ᴄʜᴀᴋᴜ ᴅᴀᴀʟ ᴋᴀʀ ᴄʜᴜᴛ ᴋᴀ ᴋʜᴏᴏɴ ᴋᴀʀ ᴅᴜɢᴀ",
"ᴛᴇʀᴇ ʙᴇʜᴇɴ ᴋ ᴄʜᴜᴛ ᴍᴇ ᴄʜᴀᴋᴜ ᴅᴀᴀʟ ᴋᴀʀ ᴄʜᴜᴛ ᴋᴀ ᴋʜᴏᴏɴ ᴋᴀʀ ᴅᴜɢᴀ",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴋᴀᴋᴛᴇ 🤱 ɢᴀʟɪ ᴋᴇ ᴋᴜᴛᴛᴏ 🦮 ᴍᴇ ʙᴀᴀᴛ ᴅᴜɴɢᴀ ᴘʜɪʀ 🍞 ʙʀᴇᴀᴅ ᴋɪ ᴛᴀʀʜ ᴋʜᴀʏᴇɴɢᴇ ᴡᴏ ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ",
"ᴅᴜᴅʜ ʜɪʟᴀᴀᴜɴɢᴀ ᴛᴇʀɪ ᴠᴀʜᴇᴇɴ ᴋᴇ ᴜᴘʀ ɴɪᴄʜᴇ 🆙🆒😙",
"ᴛᴇʀɪ ʀᴀɴᴅɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ᴘᴀᴘᴀ ᴋᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ᴍᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴀʀᴍᴀɴ ʙʜᴀɪ ᴋᴀ ʟᴀɴᴅ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀ ᴋᴏ 4sᴛ ʙᴀʟᴇ ʜɪ ᴄʜᴏᴅᴇɴɢᴇ ʀᴀɴᴅɪ ᴋᴇ",
"ᴛᴜ ᴛᴏ sᴀᴄʜɪɴ ᴋɪ ᴀᴜʟᴀᴅ ʜᴀɪ ʙᴇ",
"ᴛᴇʀɪ ᴍᴀ ᴋɪ ᴄʜᴜᴛ ʜᴜɴᴛᴇʀ ʙʜᴀɪ ᴋᴀ ᴋᴀʟᴀ ᴋᴀʟᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋᴏ sᴜᴍʏᴀ ᴍᴇ 150 ʀs ᴍᴇ ᴄʜᴏᴅᴀ ᴛʜᴀ ɴᴀ ʙʜᴏᴏʟ ɢᴀʏᴀ sᴀᴀʟᴇ",
"ᴊʜᴀᴛ ᴋᴇ ʙᴀᴀʟ ʙʜᴀɢ ᴊᴀ ʏᴀʜᴀ sᴇ ɴɪ ᴛᴏ 4sᴛ ʙᴀʟᴇ ᴄʜᴏᴅ ᴅᴇɴɢᴇ ᴛᴇᴋᴏ",
"4sᴛ ᴏᴘ ʙᴀᴋɪ sᴀʙ ʟᴀɴᴅ ᴋɪ ᴛᴏᴘɪ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋᴏ 4sᴛ ɴᴀɴɢᴀ ᴋᴀʀ ᴋᴇ ɴᴀᴄʜᴀᴜɴɢᴀ",
"ᴀɴᴅɪ ʙᴀɴᴅɪ sᴀɴᴅɪ ᴊᴏ 4sᴛ ᴋᴏ ɢᴀʟɪ ᴅᴇ ʙᴏ ʀᴀɴᴅɪ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ɢʜᴜᴛᴋᴀ ᴋʜᴀ ᴋᴇ ᴛʜᴜᴋ ᴅᴇɢᴀ ʙʜᴀɢ ᴊᴀ ɴɪ ᴛᴏ",
"sᴀᴄʜɪɴ ᴋᴀ ʟᴀɴᴅᴅᴅᴅᴅᴅ ʟᴇᴇᴇᴇᴇ ᴊᴀᴀᴀᴀᴀᴀ ᴛᴇʀɪɪɪɪɪɪɪɪɪ ʙᴀʜᴀɴɴɴ ᴋᴇᴇᴇᴇ ʟɪʏᴇᴇᴇᴇᴇᴇ",
"sᴀᴄʜɪɴ ᴛᴇʀɪɪɪɪɪɪɪɪɪ ʙᴀʜᴀɴɴɴɴɴɴɴɴɴ ᴋᴀᴀᴀᴀ 150 ʀsssss ᴅᴇɢᴀᴀᴀᴀᴀᴀᴀ ʟᴇɢᴀᴀᴀᴀ ᴋʏᴀᴀᴀᴀ",
"ᴊʜᴀᴛᴛᴛᴛ ᴋᴇᴇᴇᴇᴇ ʙᴀᴀᴀᴀʟʟʟʟʟ ᴛᴜᴜᴜᴜᴜ ᴛᴏᴏᴏᴏ sᴀᴄʜɪɴɴɴɴ ᴋɪ ᴀᴜʟᴀᴀᴀᴅᴅᴅᴅ ʜᴀɪɪɪɪ",
"ᴛᴇʀɪɪɪɪɪ ʙᴀʜᴀɴɴɴɴɴɴ 4sᴛ ᴍᴇᴇᴇᴇᴇ ᴀᴀᴀᴀᴀ ᴋᴇ ᴀᴘɴɪɪɪɪ ᴄʜᴜᴛᴛᴛ ᴅɪᴋʜᴀᴀᴀᴀᴛɪɪɪɪ ʜᴀɪɪɪɪ",
"ᴛᴇʀɪɪɪɪɪɪɪɪɪ 4sᴛ ʙᴀʟᴏᴏᴏᴏᴏ ᴘᴇᴇᴇᴇᴇ 150 ʀssss ᴍᴇ ᴄʜᴜᴅᴡᴀᴛɪɪɪɪ ʜᴀɪɪɪᴜɪɪɪɪɪ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴋᴀʟɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ᴋᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴋᴀᴀʟʟʟʟɪɪɪ ᴋᴀʟɪɪɪɪɪɪɪ ᴄʜᴜᴛᴛᴛᴛᴛᴛ ᴍᴄ ʙᴄ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ 150 ᴍᴇ ᴅᴇɢᴀ ᴋʏᴀ ʀᴇ",
"ᴛᴜ ᴛᴏ ʀᴇᴀʟ ʀᴀɴᴅɪ ᴋɪ ᴀᴜʟᴀᴅ ʜᴀɪ sᴀʟʟʟʟʟʟᴇᴇᴇ",
"ʏʀ ᴛᴇʀɪ ʙᴀʜᴀɴɴɴɴɴɴ ᴋɪ ᴄʜᴜᴛᴛᴛᴛ ᴅᴇ ᴅᴇᴇᴇᴇᴇᴇ ɴᴀᴀᴀᴀ ʀᴇᴇᴇᴇᴇ",
"ᴛᴇʀɪ ʙᴀʜᴀɴɴɴɴɴɴ ᴋɪɪɪɪɪɪɪɪɪɪ ʟᴀʟʟʟʟʟʟ ʟᴀʟʟʟʟʟʟ ᴄʜᴜᴛᴛᴛᴛᴛᴛ",
"ᴛʜᴏᴍᴀsssss ᴋᴀᴀᴀᴀ ᴍᴏᴛᴛᴛᴀᴀᴀ ʟᴀɴᴅᴅᴅᴅ ʟᴇʟᴇ ᴀᴘɴɪ ʙᴀʜᴀɴɴɴ ᴋᴇᴇᴇᴇ ʟɪʏᴇᴇᴇᴇ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ✋ ʜᴀᴛᴛʜ ᴅᴀʟᴋᴇ 👶 ʙᴀᴄᴄʜᴇ ɴɪᴋᴀʟ ᴅᴜɴɢᴀ 😍",
"ᴛᴇʀɪ ʙᴇʜɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴋᴇʟᴇ ᴋᴇ ᴄʜɪʟᴋᴇ 🍌🍌😍",
"ᴛᴇʀɪ ʙʜᴇɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴜꜱᴇʀʙᴏᴛ ʟᴀɢᴀᴀᴜɴɢᴀ ꜱᴀꜱᴛᴇ ꜱᴘᴀᴍ ᴋᴇ ᴄʜᴏᴅᴇ",
"ᴛᴇʀɪ ᴠᴀʜᴇᴇɴ ᴅʜᴀɴᴅʜᴇ ᴠᴀᴀʟɪ 😋😛",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴇ ʙʜᴏꜱᴅᴇ ᴍᴇ ᴀᴄ ʟᴀɢᴀ ᴅᴜɴɢᴀ ꜱᴀᴀʀɪ ɢᴀʀᴍɪ ɴɪᴋᴀʟ ᴊᴀᴀʏᴇɢɪ",
"ᴛᴇʀɪ ᴠᴀʜᴇᴇɴ ᴋᴏ ʜᴏʀʟɪᴄᴋꜱ ᴘᴇᴇʟᴀᴜɴɢᴀ ᴍᴀᴅᴀʀᴄʜᴏᴅ😚",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ɢᴀᴀɴᴅ ᴍᴇ ꜱᴀʀɪʏᴀ ᴅᴀᴀʟ ᴅᴜɴɢᴀ ᴍᴀᴅᴀʀᴄʜᴏᴅ ᴜꜱɪ ꜱᴀʀɪʏᴇ ᴘʀ ᴛᴀɴɢ ᴋᴇ ʙᴀᴄʜᴇ ᴘᴀɪᴅᴀ ʜᴏɴɢᴇ 😱😱",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴏ ᴋᴏʟᴋᴀᴛᴀ ᴠᴀᴀʟᴇ ᴊɪᴛᴜ ʙʜᴀɪʏᴀ ᴋᴀ ʟᴜɴᴅ ᴍᴜʙᴀʀᴀᴋ 🤩🤩",
"ᴛᴇʀɪ ᴍᴜᴍᴍʏ ᴋɪ ꜰᴀɴᴛᴀꜱʏ ʜᴜ ʟᴀᴡᴅᴇ, ᴛᴜ ᴀᴘɴɪ ʙʜᴇɴ ᴋᴏ ꜱᴍʙʜᴀᴀʟ 😈😈",
"ᴛᴇʀᴀ ᴘᴇʜʟᴀ ʙᴀᴀᴘ ʜᴜ ᴍᴀᴅᴀʀᴄʜᴏᴅ ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴠᴀʜᴇᴇɴ ᴋᴇ ʙʜᴏꜱᴅᴇ ᴍᴇ xᴠɪᴅᴇᴏꜱ.ᴄᴏᴍ ᴄʜᴀʟᴀ ᴋᴇ ᴍᴜᴛʜ ᴍᴀᴀʀᴜɴɢᴀ 🤡😹",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴀ ɢʀᴏᴜᴘ ᴠᴀᴀʟᴏɴ ꜱᴀᴀᴛʜ ᴍɪʟᴋᴇ ɢᴀɴɢ ʙᴀɴɢ ᴋʀᴜɴɢᴀ🙌🏻☠️ ",
"ᴛᴇʀɪ ɪᴛᴇᴍ ᴋɪ ɢᴀᴀɴᴅ ᴍᴇ ʟᴜɴᴅ ᴅᴀᴀʟᴋᴇ,ᴛᴇʀᴇ ᴊᴀɪꜱᴀ ᴇᴋ ᴏʀ ɴɪᴋᴀᴀʟ ᴅᴜɴɢᴀ ᴍᴀᴅᴀʀᴄʜᴏᴅ🤘🏻🙌🏻☠️ ",
"ᴀᴜᴋᴀᴀᴛ ᴍᴇ ʀᴇʜ ᴠʀɴᴀ ɢᴀᴀɴᴅ ᴍᴇ ᴅᴀɴᴅᴀ ᴅᴀᴀʟ ᴋᴇ ᴍᴜʜ ꜱᴇ ɴɪᴋᴀᴀʟ ᴅᴜɴɢᴀ ꜱʜᴀʀɪʀ ʙʜɪ ᴅᴀɴᴅᴇ ᴊᴇꜱᴀ ᴅɪᴋʜᴇɢᴀ 🙄🤭🤭",
"ᴛᴇʀɪ ᴍᴜᴍᴍʏ ᴋᴇ ꜱᴀᴀᴛʜ ʟᴜᴅᴏ ᴋʜᴇʟᴛᴇ ᴋʜᴇʟᴛᴇ ᴜꜱᴋᴇ ᴍᴜʜ ᴍᴇ ᴀᴘɴᴀ ʟᴏᴅᴀ ᴅᴇ ᴅᴜɴɢᴀ☝🏻☝🏻😬",
"ᴛᴇʀɪ ᴠᴀʜᴇᴇɴ ᴋᴏ ᴀᴘɴᴇ ʟᴜɴᴅ ᴘʀ ɪᴛɴᴀ ᴊʜᴜʟᴀᴀᴜɴɢᴀ ᴋɪ ᴊʜᴜʟᴛᴇ ᴊʜᴜʟᴛᴇ ʜɪ ʙᴀᴄʜᴀ ᴘᴀɪᴅᴀ ᴋʀ ᴅᴇɢɪ👀👯 ",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ʙᴀᴛᴛᴇʀʏ ʟᴀɢᴀ ᴋᴇ ᴘᴏᴡᴇʀʙᴀɴᴋ ʙᴀɴᴀ ᴅᴜɴɢᴀ 🔋 🔥🤩",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ᴄ++ ꜱᴛʀɪɴɢ ᴇɴᴄʀʏᴘᴛɪᴏɴ ʟᴀɢᴀ ᴅᴜɴɢᴀ ʙᴀʜᴛɪ ʜᴜʏɪ ᴄʜᴜᴛ ʀᴜᴋ ᴊᴀʏᴇɢɪɪɪɪ😈🔥😍",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴇ ɢᴀᴀɴᴅ ᴍᴇɪ ᴊʜᴀᴀᴅᴜ ᴅᴀʟ ᴋᴇ ᴍᴏʀ 🦚 ʙᴀɴᴀ ᴅᴜɴɢᴀᴀ 🤩🥵😱",
"ᴛᴇʀɪ ᴄʜᴜᴛ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ꜱʜᴏᴜʟᴅᴇʀɪɴɢ ᴋᴀʀ ᴅᴜɴɢᴀᴀ ʜɪʟᴀᴛᴇ ʜᴜʏᴇ ʙʜɪ ᴅᴀʀᴅ ʜᴏɢᴀᴀᴀ😱🤮👺",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴏ ʀᴇᴅɪ ᴘᴇ ʙᴀɪᴛʜᴀʟ ᴋᴇ ᴜꜱꜱᴇ ᴜꜱᴋɪ ᴄʜᴜᴛ ʙɪʟᴡᴀᴜɴɢᴀᴀ 💰 😵🤩",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ʙʜᴏꜱᴅɪᴋᴇ ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ 4 ʜᴏʟᴇ ʜᴀɪ ᴜɴᴍᴇ ᴍꜱᴇᴀʟ ʟᴀɢᴀ ʙᴀʜᴜᴛ ʙᴀʜᴇᴛɪ ʜᴀɪ ʙʜᴏꜰᴅɪᴋᴇ👊🤮🤢🤢",
"ᴛᴇʀɪ ʙᴀʜᴇɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ʙᴀʀɢᴀᴅ ᴋᴀ ᴘᴇᴅ ᴜɢᴀ ᴅᴜɴɢᴀᴀ ᴄᴏʀᴏɴᴀ ᴍᴇɪ ꜱᴀʙ ᴏxʏɢᴇɴ ʟᴇᴋᴀʀ ᴊᴀʏᴇɴɢᴇ🤢🤩🥳",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ꜱᴜᴅᴏ ʟᴀɢᴀ ᴋᴇ ʙɪɢꜱᴘᴀᴍ ʟᴀɢᴀ ᴋᴇ 9999 ꜰᴜᴄᴋ ʟᴀɢᴀᴀ ᴅᴜ 🤩🥳🔥",
"ᴛᴇʀɪ ᴠᴀʜᴇɴ ᴋᴇ ʙʜᴏꜱᴅɪᴋᴇ ᴍᴇɪ ʙᴇꜱᴀɴ ᴋᴇ ʟᴀᴅᴅᴜ ʙʜᴀʀ ᴅᴜɴɢᴀ🤩🥳🔥😈",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴋʜᴏᴅ ᴋᴇ ᴜꜱᴍᴇ ᴄʏʟɪɴᴅᴇʀ ⛽️ ꜰɪᴛ ᴋᴀʀᴋᴇ ᴜꜱᴍᴇᴇ ᴅᴀʟ ᴍᴀᴋʜᴀɴɪ ʙᴀɴᴀᴜɴɢᴀᴀᴀ🤩👊🔥",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ꜱʜᴇᴇꜱʜᴀ ᴅᴀʟ ᴅᴜɴɢᴀᴀᴀ ᴀᴜʀ ᴄʜᴀᴜʀᴀʜᴇ ᴘᴇ ᴛᴀᴀɴɢ ᴅᴜɴɢᴀ ʙʜᴏꜱᴅɪᴋᴇ😈😱🤩",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ᴄʀᴇᴅɪᴛ ᴄᴀʀᴅ ᴅᴀʟ ᴋᴇ ᴀɢᴇ ꜱᴇ 500 ᴋᴇ ᴋᴀᴀʀᴇ ᴋᴀᴀʀᴇ ɴᴏᴛᴇ ɴɪᴋᴀʟᴜɴɢᴀᴀ ʙʜᴏꜱᴅɪᴋᴇ💰💰🤩",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴇ ꜱᴀᴛʜ ꜱᴜᴀʀ ᴋᴀ ꜱᴇx ᴋᴀʀᴡᴀ ᴅᴜɴɢᴀᴀ ᴇᴋ ꜱᴀᴛʜ 6-6 ʙᴀᴄʜᴇ ᴅᴇɢɪ💰🔥😱",
"ᴛᴇʀɪ ʙᴀʜᴇɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ᴀᴘᴘʟᴇ ᴋᴀ 18ᴡ ᴡᴀʟᴀ ᴄʜᴀʀɢᴇʀ 🔥🤩",
"ᴛᴇʀɪ ʀᴀɴᴅɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ᴘᴀᴘᴀ ᴋᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ᴍᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴀʀᴍᴀɴ ʙʜᴀɪ ᴋᴀ ʟᴀɴᴅ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀ ᴋᴏ 4sᴛ ʙᴀʟᴇ ʜɪ ᴄʜᴏᴅᴇɴɢᴇ ʀᴀɴᴅɪ ᴋᴇ",
"ᴛᴜ ᴛᴏ sᴀᴄʜɪɴ ᴋɪ ᴀᴜʟᴀᴅ ʜᴀɪ ʙᴇ",
"ᴛᴇʀɪ ᴍᴀ ᴋɪ ᴄʜᴜᴛ ʜᴜɴᴛᴇʀ ʙʜᴀɪ ᴋᴀ ᴋᴀʟᴀ ᴋᴀʟᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋᴏ sᴜᴍʏᴀ ᴍᴇ 150 ʀs ᴍᴇ ᴄʜᴏᴅᴀ ᴛʜᴀ ɴᴀ ʙʜᴏᴏʟ ɢᴀʏᴀ sᴀᴀʟᴇ",
"ᴊʜᴀᴛ ᴋᴇ ʙᴀᴀʟ ʙʜᴀɢ ᴊᴀ ʏᴀʜᴀ sᴇ ɴɪ ᴛᴏ 4sᴛ ʙᴀʟᴇ ᴄʜᴏᴅ ᴅᴇɴɢᴇ ᴛᴇᴋᴏ",
"4sᴛ ᴏᴘ ʙᴀᴋɪ sᴀʙ ʟᴀɴᴅ ᴋɪ ᴛᴏᴘɪ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋᴏ 4sᴛ ɴᴀɴɢᴀ ᴋᴀʀ ᴋᴇ ɴᴀᴄʜᴀᴜɴɢᴀ",
"ᴀɴᴅɪ ʙᴀɴᴅɪ sᴀɴᴅɪ ᴊᴏ 4sᴛ ᴋᴏ ɢᴀʟɪ ᴅᴇ ʙᴏ ʀᴀɴᴅɪ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ɢʜᴜᴛᴋᴀ ᴋʜᴀ ᴋᴇ ᴛʜᴜᴋ ᴅᴇɢᴀ ʙʜᴀɢ ᴊᴀ ɴɪ ᴛᴏ",
"sᴀᴄʜɪɴ ᴋᴀ ʟᴀɴᴅᴅᴅᴅᴅᴅ ʟᴇᴇᴇᴇᴇ ᴊᴀᴀᴀᴀᴀᴀ ᴛᴇʀɪɪɪɪɪɪɪɪɪ ʙᴀʜᴀɴɴɴ ᴋᴇᴇᴇᴇ ʟɪʏᴇᴇᴇᴇᴇᴇ",
"sᴀᴄʜɪɴ ᴛᴇʀɪɪɪɪɪɪɪɪɪ ʙᴀʜᴀɴɴɴɴɴɴɴɴɴ ᴋᴀᴀᴀᴀ 150 ʀsssss ᴅᴇɢᴀᴀᴀᴀᴀᴀᴀ ʟᴇɢᴀᴀᴀᴀ ᴋʏᴀᴀᴀᴀ",
"ᴊʜᴀᴛᴛᴛᴛ ᴋᴇᴇᴇᴇᴇ ʙᴀᴀᴀᴀʟʟʟʟʟ ᴛᴜᴜᴜᴜᴜ ᴛᴏᴏᴏᴏ sᴀᴄʜɪɴɴɴɴ ᴋɪ ᴀᴜʟᴀᴀᴀᴅᴅᴅᴅ ʜᴀɪɪɪɪ",
"ᴛᴇʀɪɪɪɪɪ ʙᴀʜᴀɴɴɴɴɴɴ 4sᴛ ᴍᴇᴇᴇᴇᴇ ᴀᴀᴀᴀᴀ ᴋᴇ ᴀᴘɴɪɪɪɪ ᴄʜᴜᴛᴛᴛ ᴅɪᴋʜᴀᴀᴀᴀᴛɪɪɪɪ ʜᴀɪɪɪɪ",
"ᴛᴇʀɪɪɪɪɪɪɪɪɪ 4sᴛ ʙᴀʟᴏᴏᴏᴏᴏ ᴘᴇᴇᴇᴇᴇ 150 ʀssss ᴍᴇ ᴄʜᴜᴅᴡᴀᴛɪɪɪɪ ʜᴀɪɪɪᴜɪɪɪɪɪ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴋᴀʟɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ᴋᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴋᴀᴀʟʟʟʟɪɪɪ ᴋᴀʟɪɪɪɪɪɪɪ ᴄʜᴜᴛᴛᴛᴛᴛᴛ ᴍᴄ ʙᴄ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ 150 ᴍᴇ ᴅᴇɢᴀ ᴋʏᴀ ʀᴇ",
"ᴛᴜ ᴛᴏ ʀᴇᴀʟ ʀᴀɴᴅɪ ᴋɪ ᴀᴜʟᴀᴅ ʜᴀɪ sᴀʟʟʟʟʟʟᴇᴇᴇ",
"ʏʀ ᴛᴇʀɪ ʙᴀʜᴀɴɴɴɴɴɴ ᴋɪ ᴄʜᴜᴛᴛᴛᴛ ᴅᴇ ᴅᴇᴇᴇᴇᴇᴇ ɴᴀᴀᴀᴀ ʀᴇᴇᴇᴇᴇ",
"ᴛᴇʀɪ ʙᴀʜᴀɴɴɴɴɴɴ ᴋɪɪɪɪɪɪɪɪɪɪ ʟᴀʟʟʟʟʟʟ ʟᴀʟʟʟʟʟʟ ᴄʜᴜᴛᴛᴛᴛᴛᴛ",
"ᴛʜᴏᴍᴀsssss ᴋᴀᴀᴀᴀ ᴍᴏᴛᴛᴛᴀᴀᴀ ʟᴀɴᴅᴅᴅᴅ ʟᴇʟᴇ ᴀᴘɴɪ ʙᴀʜᴀɴɴɴ ᴋᴇᴇᴇᴇ ʟɪʏᴇᴇᴇᴇ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ʙᴀʜᴇɴ ᴋɪ ɢᴀᴀɴᴅ ᴍᴇɪ ᴏɴᴇᴘʟᴜꜱ ᴋᴀ ᴡʀᴀᴘ ᴄʜᴀʀɢᴇʀ 30ᴡ ʜɪɢʜ ᴘᴏᴡᴇʀ 💥😂😎",
"ᴛᴇʀɪ ʙᴀʜᴇɴ ᴋɪ ᴄʜᴜᴛ ᴋᴏ ᴀᴍᴀᴢᴏɴ ꜱᴇ ᴏʀᴅᴇʀ ᴋᴀʀᴜɴɢᴀ 10 ʀꜱ ᴍᴇɪ ᴀᴜʀ ꜰʟɪᴘᴋᴀʀᴛ ᴘᴇ 20 ʀꜱ ᴍᴇɪ ʙᴇᴄʜ ᴅᴜɴɢᴀ🤮👿😈🤖",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ʙᴀᴅɪ ʙʜᴜɴᴅ ᴍᴇ ᴢᴏᴍᴀᴛᴏ ᴅᴀʟ ᴋᴇ ꜱᴜʙᴡᴀʏ ᴋᴀ ʙꜰꜰ ᴠᴇɢ ꜱᴜʙ ᴄᴏᴍʙᴏ [15ᴄᴍ , 16 ɪɴᴄʜᴇꜱ ] ᴏʀᴅᴇʀ ᴄᴏᴅ ᴋʀᴠᴀᴜɴɢᴀ ᴏʀ ᴛᴇʀɪ ᴍᴀᴀ ᴊᴀʙ ᴅɪʟɪᴠᴇʀʏ ᴅᴇɴᴇ ᴀʏᴇɢɪ ᴛᴀʙ ᴜꜱᴘᴇ ᴊᴀᴀᴅᴜ ᴋʀᴜɴɢᴀ ᴏʀ ꜰɪʀ 9 ᴍᴏɴᴛʜ ʙᴀᴀᴅ ᴠᴏ ᴇᴋ ᴏʀ ꜰʀᴇᴇ ᴅɪʟɪᴠᴇʀʏ ᴅᴇɢɪ🙀👍🥳🔥",
"ᴛᴇʀɪ ʙʜᴇɴ ᴋɪ ᴄʜᴜᴛ ᴋᴀᴀʟɪ🙁🤣💥",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴄʜᴀɴɢᴇꜱ ᴄᴏᴍᴍɪᴛ ᴋʀᴜɢᴀ ꜰɪʀ ᴛᴇʀɪ ʙʜᴇᴇɴ ᴋɪ ᴄʜᴜᴛ ᴀᴜᴛᴏᴍᴀᴛɪᴄᴀʟʟʏ ᴜᴘᴅᴀᴛᴇ ʜᴏᴊᴀᴀʏᴇɢɪ🤖🙏🤔",
"ᴛᴇʀɪ ᴍᴀᴜꜱɪ ᴋᴇ ʙʜᴏꜱᴅᴇ ᴍᴇɪ ɪɴᴅɪᴀɴ ʀᴀɪʟᴡᴀʏ 🚂💥😂",
"ᴛᴜ ᴛᴇʀɪ ʙᴀʜᴇɴ ᴛᴇʀᴀ ᴋʜᴀɴᴅᴀɴ ꜱᴀʙ ʙᴀʜᴇɴ ᴋᴇ ʟᴀᴡᴅᴇ ʀᴀɴᴅɪ ʜᴀɪ ʀᴀɴᴅɪ 🤢✅🔥",
"ᴛᴇʀɪ ʙᴀʜᴇɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ɪᴏɴɪᴄ ʙᴏɴᴅ ʙᴀɴᴀ ᴋᴇ ᴠɪʀɢɪɴɪᴛʏ ʟᴏᴏꜱᴇ ᴋᴀʀᴡᴀ ᴅᴜɴɢᴀ ᴜꜱᴋɪ 📚 😎🤩",
"ᴛᴇʀɪ ʀᴀɴᴅɪ ᴍᴀᴀ ꜱᴇ ᴘᴜᴄʜɴᴀ ʙᴀᴀᴘ ᴋᴀ ɴᴀᴀᴍ ʙᴀʜᴇɴ ᴋᴇ ʟᴏᴅᴇᴇᴇᴇᴇ 🤩🥳😳",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴜ ᴀᴜʀ ᴛᴇʀɪ ᴍᴀᴀ ᴅᴏɴᴏ ᴋɪ ʙʜᴏꜱᴅᴇ ᴍᴇɪ ᴍᴇᴛʀᴏ ᴄʜᴀʟᴡᴀ ᴅᴜɴɢᴀ ᴍᴀᴅᴀʀxʜᴏᴅ 🚇🤩😱🥶",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴏ ɪᴛɴᴀ ᴄʜᴏᴅᴜɴɢᴀ ᴛᴇʀᴀ ʙᴀᴀᴘ ʙʜɪ ᴜꜱᴋᴏ ᴘᴀʜᴄʜᴀɴᴀɴᴇ ꜱᴇ ᴍᴀɴᴀ ᴋᴀʀ ᴅᴇɢᴀ😂👿🤩",
"ᴛᴇʀɪ ʙᴀʜᴇɴ ᴋᴇ ʙʜᴏꜱᴅᴇ ᴍᴇɪ ʜᴀɪʀ ᴅʀʏᴇʀ ᴄʜᴀʟᴀ ᴅᴜɴɢᴀᴀ💥🔥🔥",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ᴛᴇʟᴇɢʀᴀᴍ ᴋɪ ꜱᴀʀɪ ʀᴀɴᴅɪʏᴏɴ ᴋᴀ ʀᴀɴᴅɪ ᴋʜᴀɴᴀ ᴋʜᴏʟ ᴅᴜɴɢᴀᴀ👿🤮😎",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴀʟᴇxᴀ ᴅᴀʟ ᴋᴇᴇ ᴅᴊ ʙᴀᴊᴀᴜɴɢᴀᴀᴀ 🎶 ⬆️🤩💥",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴇ ʙʜᴏꜱᴅᴇ ᴍᴇɪ ɢɪᴛʜᴜʙ ᴅᴀʟ ᴋᴇ ᴀᴘɴᴀ ʙᴏᴛ ʜᴏꜱᴛ ᴋᴀʀᴜɴɢᴀᴀ 🤩👊👤😍",
"ᴛᴇʀɪ ʙᴀʜᴇɴ ᴋᴀ ᴠᴘꜱ ʙᴀɴᴀ ᴋᴇ 24*7 ʙᴀꜱʜ ᴄʜᴜᴅᴀɪ ᴄᴏᴍᴍᴀɴᴅ ᴅᴇ ᴅᴜɴɢᴀᴀ 🤩💥🔥🔥",
"ᴛᴇʀɪ ᴍᴜᴍᴍʏ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ᴛᴇʀᴇ ʟᴀɴᴅ ᴋᴏ ᴅᴀʟ ᴋᴇ ᴋᴀᴀᴛ ᴅᴜɴɢᴀ ᴍᴀᴅᴀʀᴄʜᴏᴅ 🔪😂🔥",
"ꜱᴜɴ ᴛᴇʀɪ ᴍᴀᴀ ᴋᴀ ʙʜᴏꜱᴅᴀ ᴀᴜʀ ᴛᴇʀɪ ʙᴀʜᴇɴ ᴋᴀ ʙʜɪ ʙʜᴏꜱᴅᴀ 👿😎👊",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴜᴊʜᴇ ᴅᴇᴋʜ ᴋᴇ ᴛᴇʀɪ ʀᴀɴᴅɪ ʙᴀʜᴇɴ ᴘᴇ ᴛᴀʀᴀꜱ ᴀᴛᴀ ʜᴀɪ ᴍᴜᴊʜᴇ ʙᴀʜᴇɴ ᴋᴇ ʟᴏᴅᴇᴇᴇᴇ 👿💥🤩🔥",
"ꜱᴜɴ ᴍᴀᴅᴀʀᴄʜᴏᴅ ᴊʏᴀᴅᴀ ɴᴀ ᴜᴄʜᴀʟ ᴍᴀᴀ ᴄʜᴏᴅ ᴅᴇɴɢᴇ ᴇᴋ ᴍɪɴ ᴍᴇɪ ✅🤣🔥🤩",
"ᴀᴘɴɪ ᴀᴍᴍᴀ ꜱᴇ ᴘᴜᴄʜɴᴀ ᴜꜱᴋᴏ ᴜꜱ ᴋᴀᴀʟɪ ʀᴀᴀᴛ ᴍᴇɪ ᴋᴀᴜɴ ᴄʜᴏᴅɴᴇᴇ ᴀʏᴀ ᴛʜᴀᴀᴀ! ᴛᴇʀᴇ ɪꜱ ᴘᴀᴘᴀ ᴋᴀ ɴᴀᴀᴍ ʟᴇɢɪ 😂👿😳",
"ᴛᴏʜᴀʀ ʙᴀʜɪɴ ᴄʜᴏᴅᴜ ʙʙᴀʜᴇɴ ᴋᴇ ʟᴀᴡᴅᴇ ᴜꜱᴍᴇ ᴍɪᴛᴛɪ ᴅᴀʟ ᴋᴇ ᴄᴇᴍᴇɴᴛ ꜱᴇ ʙʜᴀʀ ᴅᴜ 🏠🤢🤩💥",
"ᴛᴜᴊʜᴇ ᴀʙ ᴛᴀᴋ ɴᴀʜɪ ꜱᴍᴊʜ ᴀʏᴀ ᴋɪ ᴍᴀɪ ʜɪ ʜᴜ ᴛᴜᴊʜᴇ ᴘᴀɪᴅᴀ ᴋᴀʀɴᴇ ᴡᴀʟᴀ ʙʜᴏꜱᴅɪᴋᴇᴇ ᴀᴘɴɪ ᴍᴀᴀ ꜱᴇ ᴘᴜᴄʜ ʀᴀɴᴅɪ ᴋᴇ ʙᴀᴄʜᴇᴇᴇᴇ 🤩👊👤😍",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴇ ʙʜᴏꜱᴅᴇ ᴍᴇɪ ꜱᴘᴏᴛɪꜰʏ ᴅᴀʟ ᴋᴇ ʟᴏꜰɪ ʙᴀᴊᴀᴜɴɢᴀ ᴅɪɴ ʙʜᴀʀ 😍🎶🎶💥",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴀ ɴᴀʏᴀ ʀᴀɴᴅɪ ᴋʜᴀɴᴀ ᴋʜᴏʟᴜɴɢᴀ ᴄʜɪɴᴛᴀ ᴍᴀᴛ ᴋᴀʀ 👊🤣🤣😳",
"ᴛᴇʀᴀ ʙᴀᴀᴘ ʜᴜ ʙʜᴏꜱᴅɪᴋᴇ ᴛᴇʀɪ ᴍᴀᴀ ᴋᴏ ʀᴀɴᴅɪ ᴋʜᴀɴᴇ ᴘᴇ ᴄʜᴜᴅᴡᴀ ᴋᴇ ᴜꜱ ᴘᴀɪꜱᴇ ᴋɪ ᴅᴀᴀʀᴜ ᴘᴇᴇᴛᴀ ʜᴜ 🍷🤩🔥",
"ᴛᴇʀɪ ʙᴀʜᴇɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ᴀᴘɴᴀ ʙᴀᴅᴀ ꜱᴀ ʟᴏᴅᴀ ɢʜᴜꜱꜱᴀ ᴅᴜɴɢᴀᴀ ᴋᴀʟʟᴀᴀᴘ ᴋᴇ ᴍᴀʀ ᴊᴀʏᴇɢɪ 🤩😳😳🔥",
"ᴛᴏʜᴀʀ ᴍᴜᴍᴍʏ ᴋɪ ᴄʜᴜᴛ ᴍᴇɪ ᴘᴜʀɪ ᴋɪ ᴘᴜʀɪ ᴋɪɴɢꜰɪꜱʜᴇʀ ᴋɪ ʙᴏᴛᴛʟᴇ ᴅᴀʟ ᴋᴇ ᴛᴏᴅ ᴅᴜɴɢᴀ ᴀɴᴅᴇʀ ʜɪ 😱😂🤩",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴏ ɪᴛɴᴀ ᴄʜᴏᴅᴜɴɢᴀ ᴋɪ ꜱᴀᴘɴᴇ ᴍᴇɪ ʙʜɪ ᴍᴇʀɪ ᴄʜᴜᴅᴀɪ ʏᴀᴀᴅ ᴋᴀʀᴇɢɪ ʀᴀɴᴅɪ 🥳😍👊💥",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴜᴍᴍʏ ᴀᴜʀ ʙᴀʜᴇɴ ᴋᴏ ᴅᴀᴜᴅᴀ ᴅᴀᴜᴅᴀ ɴᴇ ᴄʜᴏᴅᴜɴɢᴀ ᴜɴᴋᴇ ɴᴏ ʙᴏʟɴᴇ ᴘᴇ ʙʜɪ ʟᴀɴᴅ ɢʜᴜꜱᴀ ᴅᴜɴɢᴀ ᴀɴᴅᴇʀ ᴛᴀᴋ 😎😎🤣🔥",
"ᴛᴇʀɪ ᴍᴜᴍᴍʏ ᴋɪ ᴄʜᴜᴛ ᴋᴏ ᴏɴʟɪɴᴇ ᴏʟx ᴘᴇ ʙᴇᴄʜᴜɴɢᴀ ᴀᴜʀ ᴘᴀɪꜱᴇ ꜱᴇ ᴛᴇʀɪ ʙᴀʜᴇɴ ᴋᴀ ᴋᴏᴛʜᴀ ᴋʜᴏʟ ᴅᴜɴɢᴀ 😎🤩😝😍",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴇ ʙʜᴏꜱᴅᴀ ɪᴛɴᴀ ᴄʜᴏᴅᴜɴɢᴀ ᴋɪ ᴛᴜ ᴄᴀʜ ᴋᴇ ʙʜɪ ᴡᴏ ᴍᴀꜱᴛ ᴄʜᴜᴅᴀɪ ꜱᴇ ᴅᴜʀ ɴʜɪ ᴊᴀ ᴘᴀʏᴇɢᴀᴀ 😏😏🤩😍",
"ꜱᴜɴ ʙᴇ ʀᴀɴᴅɪ ᴋɪ ᴀᴜʟᴀᴀᴅ ᴛᴜ ᴀᴘɴɪ ʙᴀʜᴇɴ ꜱᴇ ꜱᴇᴇᴋʜ ᴋᴜᴄʜ ᴋᴀɪꜱᴇ ɢᴀᴀɴᴅ ᴍᴀʀᴡᴀᴛᴇ ʜᴀɪ😏🤬🔥💥",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋᴀ ʏᴀᴀʀ ʜᴜ ᴍᴇɪ ᴀᴜʀ ᴛᴇʀɪ ʙᴀʜᴇɴ ᴋᴀ ᴘʏᴀᴀʀ ʜᴜ ᴍᴇɪ ᴀᴊᴀ ᴍᴇʀᴀ ʟᴀɴᴅ ᴄʜᴏᴏꜱ ʟᴇ 🤩🤣💥",
"ᴛᴇʀɪ ʙʜᴇɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴜꜱᴇʀʙᴏᴛ ʟᴀɢᴀᴀᴜɴɢᴀ ꜱᴀꜱᴛᴇ ꜱᴘᴀᴍ ᴋᴇ ᴄʜᴏᴅᴇ",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ɢᴀᴀɴᴅ ᴍᴇ ꜱᴀʀɪʏᴀ ᴅᴀᴀʟ ᴅᴜɴɢᴀ ᴍᴀᴅᴀʀᴄʜᴏᴅ ᴜꜱɪ ꜱᴀʀɪʏᴇ ᴘʀ ᴛᴀɴɢ ᴋᴇ ʙᴀᴄʜᴇ ᴘᴀɪᴅᴀ ʜᴏɴɢᴇ 😱😱",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ✋ ʜᴀᴛᴛʜ ᴅᴀʟᴋᴇ 👶 ʙᴀᴄᴄʜᴇ ɴɪᴋᴀʟ ᴅᴜɴɢᴀ 😍",
"ᴛᴇʀɪ ʙᴇʜɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴋᴇʟᴇ ᴋᴇ ᴄʜɪʟᴋᴇ 🤤🤤",
"ᴛᴇʀɪ ʀᴀɴᴅɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ᴘᴀᴘᴀ ᴋᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ᴍᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴀʀᴍᴀɴ ʙʜᴀɪ ᴋᴀ ʟᴀɴᴅ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀ ᴋᴏ 4sᴛ ʙᴀʟᴇ ʜɪ ᴄʜᴏᴅᴇɴɢᴇ ʀᴀɴᴅɪ ᴋᴇ",
"ᴛᴜ ᴛᴏ sᴀᴄʜɪɴ ᴋɪ ᴀᴜʟᴀᴅ ʜᴀɪ ʙᴇ",
"ᴛᴇʀɪ ᴍᴀ ᴋɪ ᴄʜᴜᴛ ʜᴜɴᴛᴇʀ ʙʜᴀɪ ᴋᴀ ᴋᴀʟᴀ ᴋᴀʟᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋᴏ sᴜᴍʏᴀ ᴍᴇ 150 ʀs ᴍᴇ ᴄʜᴏᴅᴀ ᴛʜᴀ ɴᴀ ʙʜᴏᴏʟ ɢᴀʏᴀ sᴀᴀʟᴇ",
"ᴊʜᴀᴛ ᴋᴇ ʙᴀᴀʟ ʙʜᴀɢ ᴊᴀ ʏᴀʜᴀ sᴇ ɴɪ ᴛᴏ 4sᴛ ʙᴀʟᴇ ᴄʜᴏᴅ ᴅᴇɴɢᴇ ᴛᴇᴋᴏ",
"4sᴛ ᴏᴘ ʙᴀᴋɪ sᴀʙ ʟᴀɴᴅ ᴋɪ ᴛᴏᴘɪ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋᴏ 4sᴛ ɴᴀɴɢᴀ ᴋᴀʀ ᴋᴇ ɴᴀᴄʜᴀᴜɴɢᴀ",
"ᴀɴᴅɪ ʙᴀɴᴅɪ sᴀɴᴅɪ ᴊᴏ 4sᴛ ᴋᴏ ɢᴀʟɪ ᴅᴇ ʙᴏ ʀᴀɴᴅɪ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ɢʜᴜᴛᴋᴀ ᴋʜᴀ ᴋᴇ ᴛʜᴜᴋ ᴅᴇɢᴀ ʙʜᴀɢ ᴊᴀ ɴɪ ᴛᴏ",
"sᴀᴄʜɪɴ ᴋᴀ ʟᴀɴᴅᴅᴅᴅᴅᴅ ʟᴇᴇᴇᴇᴇ ᴊᴀᴀᴀᴀᴀᴀ ᴛᴇʀɪɪɪɪɪɪɪɪɪ ʙᴀʜᴀɴɴɴ ᴋᴇᴇᴇᴇ ʟɪʏᴇᴇᴇᴇᴇᴇ",
"sᴀᴄʜɪɴ ᴛᴇʀɪɪɪɪɪɪɪɪɪ ʙᴀʜᴀɴɴɴɴɴɴɴɴɴ ᴋᴀᴀᴀᴀ 150 ʀsssss ᴅᴇɢᴀᴀᴀᴀᴀᴀᴀ ʟᴇɢᴀᴀᴀᴀ ᴋʏᴀᴀᴀᴀ",
"ᴊʜᴀᴛᴛᴛᴛ ᴋᴇᴇᴇᴇᴇ ʙᴀᴀᴀᴀʟʟʟʟʟ ᴛᴜᴜᴜᴜᴜ ᴛᴏᴏᴏᴏ sᴀᴄʜɪɴɴɴɴ ᴋɪ ᴀᴜʟᴀᴀᴀᴅᴅᴅᴅ ʜᴀɪɪɪɪ",
"ᴛᴇʀɪɪɪɪɪ ʙᴀʜᴀɴɴɴɴɴɴ 4sᴛ ᴍᴇᴇᴇᴇᴇ ᴀᴀᴀᴀᴀ ᴋᴇ ᴀᴘɴɪɪɪɪ ᴄʜᴜᴛᴛᴛ ᴅɪᴋʜᴀᴀᴀᴀᴛɪɪɪɪ ʜᴀɪɪɪɪ",
"ᴛᴇʀɪɪɪɪɪɪɪɪɪ 4sᴛ ʙᴀʟᴏᴏᴏᴏᴏ ᴘᴇᴇᴇᴇᴇ 150 ʀssss ᴍᴇ ᴄʜᴜᴅᴡᴀᴛɪɪɪɪ ʜᴀɪɪɪᴜɪɪɪɪɪ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴋᴀʟɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ᴋᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴋᴀᴀʟʟʟʟɪɪɪ ᴋᴀʟɪɪɪɪɪɪɪ ᴄʜᴜᴛᴛᴛᴛᴛᴛ ᴍᴄ ʙᴄ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ 150 ᴍᴇ ᴅᴇɢᴀ ᴋʏᴀ ʀᴇ",
"ᴛᴜ ᴛᴏ ʀᴇᴀʟ ʀᴀɴᴅɪ ᴋɪ ᴀᴜʟᴀᴅ ʜᴀɪ sᴀʟʟʟʟʟʟᴇᴇᴇ",
"ʏʀ ᴛᴇʀɪ ʙᴀʜᴀɴɴɴɴɴɴ ᴋɪ ᴄʜᴜᴛᴛᴛᴛ ᴅᴇ ᴅᴇᴇᴇᴇᴇᴇ ɴᴀᴀᴀᴀ ʀᴇᴇᴇᴇᴇ",
"ᴛᴇʀɪ ʙᴀʜᴀɴɴɴɴɴɴ ᴋɪɪɪɪɪɪɪɪɪɪ ʟᴀʟʟʟʟʟʟ ʟᴀʟʟʟʟʟʟ ᴄʜᴜᴛᴛᴛᴛᴛᴛ",
"ᴛʜᴏᴍᴀsssss ᴋᴀᴀᴀᴀ ᴍᴏᴛᴛᴛᴀᴀᴀ ʟᴀɴᴅᴅᴅᴅ ʟᴇʟᴇ ᴀᴘɴɪ ʙᴀʜᴀɴɴɴ ᴋᴇᴇᴇᴇ ʟɪʏᴇᴇᴇᴇ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ꜱᴜᴛʟɪ ʙᴏᴍʙ ꜰᴏᴅ ᴅᴜɴɢᴀ ᴛᴇʀɪ ᴍᴀᴀ ᴋɪ ᴊʜᴀᴀᴛᴇ ᴊᴀʟ ᴋᴇ ᴋʜᴀᴀᴋ ʜᴏ ᴊᴀʏᴇɢɪ💣💋",
"ᴛᴇʀɪ ᴠᴀʜᴇᴇɴ ᴋᴏ ʜᴏʀʟɪᴄᴋꜱ ᴘᴇᴇʟᴀᴋᴇ ᴄʜᴏᴅᴜɴɢᴀ ᴍᴀᴅᴀʀᴄʜᴏᴅ😚",
"ᴛᴇʀɪ ɪᴛᴇᴍ ᴋɪ ɢᴀᴀɴᴅ ᴍᴇ ʟᴜɴᴅ ᴅᴀᴀʟᴋᴇ,ᴛᴇʀᴇ ᴊᴀɪꜱᴀ ᴇᴋ ᴏʀ ɴɪᴋᴀᴀʟ ᴅᴜɴɢᴀ ᴍᴀᴅᴀʀᴄʜᴏᴅ😆🤤💋",
"ᴛᴇʀɪ ᴠᴀʜᴇᴇɴ ᴋᴏ ᴀᴘɴᴇ ʟᴜɴᴅ ᴘʀ ɪᴛɴᴀ ᴊʜᴜʟᴀᴀᴜɴɢᴀ ᴋɪ ᴊʜᴜʟᴛᴇ ᴊʜᴜʟᴛᴇ ʜɪ ʙᴀᴄʜᴀ ᴘᴀɪᴅᴀ ᴋʀ ᴅᴇɢɪ 💦💋",
"ꜱᴜᴀʀ ᴋᴇ ᴘɪʟʟᴇ ᴛᴇʀɪ ᴍᴀᴀᴋᴏ ꜱᴀᴅᴀᴋ ᴘʀ ʟɪᴛᴀᴋᴇ ᴄʜᴏᴅ ᴅᴜɴɢᴀ 😂😆🤤",
"ᴀʙᴇ ᴛᴇʀɪ ᴍᴀᴀᴋᴀ ʙʜᴏꜱᴅᴀ ᴍᴀᴅᴇʀᴄʜᴏᴏᴅ ᴋʀ ᴘɪʟʟᴇ ᴘᴀᴘᴀ ꜱᴇ ʟᴀᴅᴇɢᴀ ᴛᴜ 😼😂🤤",
"ɢᴀʟɪ ɢᴀʟɪ ɴᴇ ꜱʜᴏʀ ʜᴇ ᴛᴇʀɪ ᴍᴀᴀ ʀᴀɴᴅɪ ᴄʜᴏʀ ʜᴇ 💋💋💦",
"ᴀʙᴇ ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋᴏ ᴄʜᴏᴅᴜ ʀᴀɴᴅɪᴋᴇ ᴘɪʟʟᴇ ᴋᴜᴛᴛᴇ ᴋᴇ ᴄʜᴏᴅᴇ 😂👻🔥",
"ᴛᴇʀɪ ᴍᴀᴀᴋᴏ ᴀɪꜱᴇ ᴄʜᴏᴅᴀ ᴀɪꜱᴇ ᴄʜᴏᴅᴀ ᴛᴇʀɪ ᴍᴀᴀᴀ ʙᴇᴅ ᴘᴇʜɪ ᴍᴜᴛʜ ᴅɪᴀ 💦💦💦💦",
"ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋᴇ ʙʜᴏꜱᴅᴇ ᴍᴇ ᴀᴀᴀɢ ʟᴀɢᴀᴅɪᴀ ᴍᴇʀᴀ ᴍᴏᴛᴀ ʟᴜɴᴅ ᴅᴀʟᴋᴇ 🔥🔥💦😆😆",
"ʀᴀɴᴅɪᴋᴇ ʙᴀᴄʜʜᴇ ᴛᴇʀɪ ᴍᴀᴀᴋᴏ ᴄʜᴏᴅᴜ ᴄʜᴀʟ ɴɪᴋᴀʟ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴋɪᴛɴᴀ ᴄʜᴏᴅᴜ ᴛᴇʀɪ ʀᴀɴᴅɪ ᴍᴀᴀᴋɪ ᴄʜᴜᴛʜ ᴀʙʙ ᴀᴘɴɪ ʙᴇʜᴇɴ ᴋᴏ ʙʜᴇᴊ 😆👻🤤",
"ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋᴏᴛᴏ ᴄʜᴏᴅ ᴄʜᴏᴅᴋᴇ ᴘᴜʀᴀ ꜰᴀᴀᴅ ᴅɪᴀ ᴄʜᴜᴛʜ ᴀʙʙ ᴛᴇʀɪ ɢꜰ ᴋᴏ ʙʜᴇᴊ 😆💦🤤",
"ᴛᴇʀɪ ɢꜰ ᴋᴏ ᴇᴛɴᴀ ᴄʜᴏᴅᴀ ʙᴇʜᴇɴ ᴋᴇ ʟᴏᴅᴇ ᴛᴇʀɪ ɢꜰ ᴛᴏ ᴍᴇʀɪ ʀᴀɴᴅɪ ʙᴀɴɢᴀʏɪ ᴀʙʙ ᴄʜᴀʟ ᴛᴇʀɪ ᴍᴀᴀᴋᴏ ᴄʜᴏᴅᴛᴀ ꜰɪʀꜱᴇ ♥️💦😆😆😆😆",
"ʜᴀʀɪ ʜᴀʀɪ ɢʜᴀᴀꜱ ᴍᴇ ᴊʜᴏᴘᴅᴀ ᴛᴇʀɪ ᴍᴀᴀᴋᴀ ʙʜᴏꜱᴅᴀ 🤣🤣💋💦",
"ᴄʜᴀʟ ᴛᴇʀᴇ ʙᴀᴀᴘ ᴋᴏ ʙʜᴇᴊ ᴛᴇʀᴀ ʙᴀꜱᴋᴀ ɴʜɪ ʜᴇ ᴘᴀᴘᴀ ꜱᴇ ʟᴀᴅᴇɢᴀ ᴛᴜ",
"ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋɪ ᴄʜᴜᴛʜ ᴍᴇ ʙᴏᴍʙ ᴅᴀʟᴋᴇ ᴜᴅᴀ ᴅᴜɴɢᴀ ᴍᴀᴀᴋᴇ ʟᴀᴡᴅᴇ",
"ᴛᴇʀɪ ᴍᴀᴀᴋᴏ ᴛʀᴀɪɴ ᴍᴇ ʟᴇᴊᴀᴋᴇ ᴛᴏᴘ ʙᴇᴅ ᴘᴇ ʟɪᴛᴀᴋᴇ ᴄʜᴏᴅ ᴅᴜɴɢᴀ ꜱᴜᴀʀ ᴋᴇ ᴘɪʟʟᴇ 🤣🤣💋💋",
"ᴛᴇʀɪ ᴍᴀᴀᴀᴋᴇ ɴᴜᴅᴇꜱ ɢᴏᴏɢʟᴇ ᴘᴇ ᴜᴘʟᴏᴀᴅ ᴋᴀʀᴅᴜɴɢᴀ ʙᴇʜᴇɴ ᴋᴇ ʟᴀᴇᴡᴅᴇ 👻🔥",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀᴀᴀᴋᴇ ɴᴜᴅᴇꜱ ɢᴏᴏɢʟᴇ ᴘᴇ ᴜᴘʟᴏᴀᴅ ᴋᴀʀᴅᴜɴɢᴀ ʙᴇʜᴇɴ ᴋᴇ ʟᴀᴇᴡᴅᴇ 👻🔥",
"ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋᴏ ᴄʜᴏᴅ ᴄʜᴏᴅᴋᴇ ᴠɪᴅᴇᴏ ʙᴀɴᴀᴋᴇ xɴxx.ᴄᴏᴍ ᴘᴇ ɴᴇᴇʟᴀᴍ ᴋᴀʀᴅᴜɴɢᴀ ᴋᴜᴛᴛᴇ ᴋᴇ ᴘɪʟʟᴇ 💦💋",
"ᴛᴇʀɪ ᴍᴀᴀᴀᴋɪ ᴄʜᴜᴅᴀɪ ᴋᴏ ᴘᴏʀɴʜᴜʙ.ᴄᴏᴍ ᴘᴇ ᴜᴘʟᴏᴀᴅ ᴋᴀʀᴅᴜɴɢᴀ ꜱᴜᴀʀ ᴋᴇ ᴄʜᴏᴅᴇ 🤣💋💦",
"ᴀʙᴇ ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋᴏ ᴄʜᴏᴅᴜ ʀᴀɴᴅɪᴋᴇ ʙᴀᴄʜʜᴇ ᴛᴇʀᴇᴋᴏ ᴄʜᴀᴋᴋᴏ ꜱᴇ ᴘɪʟᴡᴀᴠᴜɴɢᴀ ʀᴀɴᴅɪᴋᴇ ʙᴀᴄʜʜᴇ 🤣🤣",
"ᴛᴇʀɪ ᴍᴀᴀᴋɪ ᴄʜᴜᴛʜ ꜰᴀᴀᴅᴋᴇ ʀᴀᴋᴅɪᴀ ᴍᴀᴀᴋᴇ ʟᴏᴅᴇ ᴊᴀᴀ ᴀʙʙ ꜱɪʟᴡᴀʟᴇ 👄👄",
"ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋɪ ᴄʜᴜᴛʜ ᴍᴇ ᴍᴇʀᴀ ʟᴜɴᴅ ᴋᴀᴀʟᴀ",
"ᴛᴇʀɪ ʙᴇʜᴇɴ ʟᴇᴛɪ ᴍᴇʀɪ ʟᴜɴᴅ ʙᴀᴅᴇ ᴍᴀꜱᴛɪ ꜱᴇ ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋᴏ ᴍᴇɴᴇ ᴄʜᴏᴅ ᴅᴀʟᴀ ʙᴏʜᴏᴛ ꜱᴀꜱᴛᴇ ꜱᴇ",
"ʙᴇᴛᴇ ᴛᴜ ʙᴀᴀᴘ ꜱᴇ ʟᴇɢᴀ ᴘᴀɴɢᴀ ᴛᴇʀɪ ᴍᴀᴀᴀ ᴋᴏ ᴄʜᴏᴅ ᴅᴜɴɢᴀ ᴋᴀʀᴋᴇ ɴᴀɴɢᴀ 💦💋",
"ʜᴀʜᴀʜᴀʜ ᴍᴇʀᴇ ʙᴇᴛᴇ ᴀɢʟɪ ʙᴀᴀʀ ᴀᴘɴɪ ᴍᴀᴀᴋᴏ ʟᴇᴋᴇ ᴀᴀʏᴀ ᴍᴀᴛʜ ᴋᴀᴛ ᴏʀ ᴍᴇʀᴇ ᴍᴏᴛᴇ ʟᴜɴᴅ ꜱᴇ ᴄʜᴜᴅᴡᴀʏᴀ ᴍᴀᴛʜ ᴋᴀʀ",
"ᴄʜᴀʟ ʙᴇᴛᴀ ᴛᴜᴊʜᴇ ᴍᴀᴀꜰ ᴋɪᴀ 🤣 ᴀʙʙ ᴀᴘɴɪ ɢꜰ ᴋᴏ ʙʜᴇᴊ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ꜱʜᴀʀᴀᴍ ᴋᴀʀ ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋᴀ ʙʜᴏꜱᴅᴀ ᴋɪᴛɴᴀ ɢᴀᴀʟɪᴀ ꜱᴜɴᴡᴀʏᴇɢᴀ ᴀᴘɴɪ ᴍᴀᴀᴀ ʙᴇʜᴇɴ ᴋᴇ ᴜᴘᴇʀ",
"ᴀʙᴇ ʀᴀɴᴅɪᴋᴇ ʙᴀᴄʜʜᴇ ᴀᴜᴋᴀᴛ ɴʜɪ ʜᴇᴛᴏ ᴀᴘɴɪ ʀᴀɴᴅɪ ᴍᴀᴀᴋᴏ ʟᴇᴋᴇ ᴀᴀʏᴀ ᴍᴀᴛʜ ᴋᴀʀ ʜᴀʜᴀʜᴀʜᴀ",
"ᴋɪᴅᴢ ᴍᴀᴅᴀʀᴄʜᴏᴅ ᴛᴇʀɪ ᴍᴀᴀᴋᴏ ᴄʜᴏᴅ ᴄʜᴏᴅᴋᴇ ᴛᴇʀʀ ʟɪʏᴇ ʙʜᴀɪ ᴅᴇᴅɪʏᴀ",
"ᴊᴜɴɢʟᴇ ᴍᴇ ɴᴀᴄʜᴛᴀ ʜᴇ ᴍᴏʀᴇ ᴛᴇʀɪ ᴍᴀᴀᴋɪ ᴄʜᴜᴅᴀɪ ᴅᴇᴋᴋᴇ ꜱᴀʙ ʙᴏʟᴛᴇ ᴏɴᴄᴇ ᴍᴏʀᴇ ᴏɴᴄᴇ ᴍᴏʀᴇ 🤣🤣💦💋",
"ɢᴀʟɪ ɢᴀʟɪ ᴍᴇ ʀᴇʜᴛᴀ ʜᴇ ꜱᴀɴᴅ ᴛᴇʀɪ ᴍᴀᴀᴋᴏ ᴄʜᴏᴅ ᴅᴀʟᴀ ᴏʀ ʙᴀɴᴀ ᴅɪᴀ ʀᴀɴᴅ 🤤🤣",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ꜱᴀʙ ʙᴏʟᴛᴇ ᴍᴜᴊʜᴋᴏ ᴘᴀᴘᴀ ᴋʏᴏᴜɴᴋɪ ᴍᴇɴᴇ ʙᴀɴᴀᴅɪᴀ ᴛᴇʀɪ ᴍᴀᴀᴋᴏ ᴘʀᴇɢɴᴇɴᴛ 🤣🤣",
"ꜱᴜᴀʀ ᴋᴇ ᴘɪʟʟᴇ ᴛᴇʀɪ ᴍᴀᴀᴋɪ ᴄʜᴜᴛʜ ᴍᴇ ꜱᴜᴀʀ ᴋᴀ ʟᴏᴜᴅᴀ ᴏʀ ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋɪ ᴄʜᴜᴛʜ ᴍᴇ ᴍᴇʀᴀ ʟᴏᴅᴀ",
"ᴄʜᴀʟ ᴄʜᴀʟ ᴀᴘɴɪ ᴍᴀᴀᴋɪ ᴄʜᴜᴄʜɪʏᴀ ᴅɪᴋᴀ",
"ʜᴀʜᴀʜᴀʜᴀ ʙᴀᴄʜʜᴇ ᴛᴇʀɪ ᴍᴀᴀᴀᴋᴏ ᴄʜᴏᴅ ᴅɪᴀ ɴᴀɴɢᴀ ᴋᴀʀᴋᴇ",
"ᴛᴇʀɪ ɢꜰ ʜᴇ ʙᴀᴅɪ ꜱᴇxʏ ᴜꜱᴋᴏ ᴘɪʟᴀᴋᴇ ᴄʜᴏᴏᴅᴇɴɢᴇ ᴘᴇᴘꜱɪ",
"2 ʀᴜᴘᴀʏ ᴋɪ ᴘᴇᴘꜱɪ ᴛᴇʀɪ ᴍᴜᴍᴍʏ ꜱᴀʙꜱᴇ ꜱᴇxʏ 💋💦",
"ᴛᴇʀɪ ᴍᴀᴀᴋᴏ ᴄʜᴇᴇᴍꜱ ꜱᴇ ᴄʜᴜᴅᴡᴀᴠᴜɴɢᴀ ᴍᴀᴅᴇʀᴄʜᴏᴏᴅ ᴋᴇ ᴘɪʟʟᴇ 💦🤣",
"ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋɪ ᴄʜᴜᴛʜ ᴍᴇ ᴍᴜᴛʜᴋᴇ ꜰᴀʀᴀʀ ʜᴏᴊᴀᴠᴜɴɢᴀ ʜᴜɪ ʜᴜɪ ʜᴜɪ",
"ꜱᴘᴇᴇᴅ ʟᴀᴀᴀ ᴛᴇʀɪ ʙᴇʜᴇɴ ᴄʜᴏᴅᴜ ʀᴀɴᴅɪᴋᴇ ᴘɪʟʟᴇ 💋💦🤣",
"ᴀʀᴇ ʀᴇ ᴍᴇʀᴇ ʙᴇᴛᴇ ᴋʏᴏᴜɴ ꜱᴘᴇᴇᴅ ᴘᴀᴋᴀᴅ ɴᴀ ᴘᴀᴀᴀ ʀᴀʜᴀ ᴀᴘɴᴇ ʙᴀᴀᴘ ᴋᴀ ʜᴀʜᴀʜ🤣🤣",
"ꜱᴜɴ ꜱᴜɴ ꜱᴜᴀʀ ᴋᴇ ᴘɪʟʟᴇ ᴊʜᴀɴᴛᴏ ᴋᴇ ꜱᴏᴜᴅᴀɢᴀʀ ᴀᴘɴɪ ᴍᴜᴍᴍʏ ᴋɪ ɴᴜᴅᴇꜱ ʙʜᴇᴊ",
"ᴀʙᴇ ꜱᴜɴ ʟᴏᴅᴇ ᴛᴇʀɪ ʙᴇʜᴇɴ ᴋᴀ ʙʜᴏꜱᴅᴀ ꜰᴀᴀᴅ ᴅᴜɴɢᴀ",
"ᴛᴇʀɪ ᴍᴀᴀᴋᴏ ᴋʜᴜʟᴇ ʙᴀᴊᴀʀ ᴍᴇ ᴄʜᴏᴅ ᴅᴀʟᴀ 🤣🤣💋",
"ᴛᴇʀɪ ʀᴀɴᴅɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ᴘᴀᴘᴀ ᴋᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ᴍᴀ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴀʀᴍᴀɴ ʙʜᴀɪ ᴋᴀ ʟᴀɴᴅ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ᴍᴀ ᴋᴏ 4sᴛ ʙᴀʟᴇ ʜɪ ᴄʜᴏᴅᴇɴɢᴇ ʀᴀɴᴅɪ ᴋᴇ",
"ᴛᴜ ᴛᴏ sᴀᴄʜɪɴ ᴋɪ ᴀᴜʟᴀᴅ ʜᴀɪ ʙᴇ",
"ᴛᴇʀɪ ᴍᴀ ᴋɪ ᴄʜᴜᴛ ʜᴜɴᴛᴇʀ ʙʜᴀɪ ᴋᴀ ᴋᴀʟᴀ ᴋᴀʟᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋᴏ sᴜᴍʏᴀ ᴍᴇ 150 ʀs ᴍᴇ ᴄʜᴏᴅᴀ ᴛʜᴀ ɴᴀ ʙʜᴏᴏʟ ɢᴀʏᴀ sᴀᴀʟᴇ",
"ᴊʜᴀᴛ ᴋᴇ ʙᴀᴀʟ ʙʜᴀɢ ᴊᴀ ʏᴀʜᴀ sᴇ ɴɪ ᴛᴏ 4sᴛ ʙᴀʟᴇ ᴄʜᴏᴅ ᴅᴇɴɢᴇ ᴛᴇᴋᴏ",
"4sᴛ ᴏᴘ ʙᴀᴋɪ sᴀʙ ʟᴀɴᴅ ᴋɪ ᴛᴏᴘɪ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋᴏ 4sᴛ ɴᴀɴɢᴀ ᴋᴀʀ ᴋᴇ ɴᴀᴄʜᴀᴜɴɢᴀ",
"ᴀɴᴅɪ ʙᴀɴᴅɪ sᴀɴᴅɪ ᴊᴏ 4sᴛ ᴋᴏ ɢᴀʟɪ ᴅᴇ ʙᴏ ʀᴀɴᴅɪ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ɢʜᴜᴛᴋᴀ ᴋʜᴀ ᴋᴇ ᴛʜᴜᴋ ᴅᴇɢᴀ ʙʜᴀɢ ᴊᴀ ɴɪ ᴛᴏ",
"sᴀᴄʜɪɴ ᴋᴀ ʟᴀɴᴅᴅᴅᴅᴅᴅ ʟᴇᴇᴇᴇᴇ ᴊᴀᴀᴀᴀᴀᴀ ᴛᴇʀɪɪɪɪɪɪɪɪɪ ʙᴀʜᴀɴɴɴ ᴋᴇᴇᴇᴇ ʟɪʏᴇᴇᴇᴇᴇᴇ",
"sᴀᴄʜɪɴ ᴛᴇʀɪɪɪɪɪɪɪɪɪ ʙᴀʜᴀɴɴɴɴɴɴɴɴɴ ᴋᴀᴀᴀᴀ 150 ʀsssss ᴅᴇɢᴀᴀᴀᴀᴀᴀᴀ ʟᴇɢᴀᴀᴀᴀ ᴋʏᴀᴀᴀᴀ",
"ᴊʜᴀᴛᴛᴛᴛ ᴋᴇᴇᴇᴇᴇ ʙᴀᴀᴀᴀʟʟʟʟʟ ᴛᴜᴜᴜᴜᴜ ᴛᴏᴏᴏᴏ sᴀᴄʜɪɴɴɴɴ ᴋɪ ᴀᴜʟᴀᴀᴀᴅᴅᴅᴅ ʜᴀɪɪɪɪ",
"ᴛᴇʀɪɪɪɪɪ ʙᴀʜᴀɴɴɴɴɴɴ 4sᴛ ᴍᴇᴇᴇᴇᴇ ᴀᴀᴀᴀᴀ ᴋᴇ ᴀᴘɴɪɪɪɪ ᴄʜᴜᴛᴛᴛ ᴅɪᴋʜᴀᴀᴀᴀᴛɪɪɪɪ ʜᴀɪɪɪɪ",
"ᴛᴇʀɪɪɪɪɪɪɪɪɪ 4sᴛ ʙᴀʟᴏᴏᴏᴏᴏ ᴘᴇᴇᴇᴇᴇ 150 ʀssss ᴍᴇ ᴄʜᴜᴅᴡᴀᴛɪɪɪɪ ʜᴀɪɪɪᴜɪɪɪɪɪ",
"𝗦𝗔𝗡𝗔𝗧𝗔𝗡𝗜 [ sᴀᴄʜɪɴ sᴀɴᴀᴛᴀɴɪ ] 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣𝗣𝗣𝗣𝗣 𝗛𝗔𝗜 𝗥𝗔𝗡𝗗𝗜 𝗞𝗘",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴋᴀʟɪ ᴄʜᴜᴛ ᴍᴇ ᴛʜᴏᴍᴀs ᴋᴀ ʟᴀɴᴅ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴋᴀᴀʟʟʟʟɪɪɪ ᴋᴀʟɪɪɪɪɪɪɪ ᴄʜᴜᴛᴛᴛᴛᴛᴛ ᴍᴄ ʙᴄ",
"ᴛᴇʀɪ ʙᴀʜᴀɴ ᴋɪ ᴄʜᴜᴛ 150 ᴍᴇ ᴅᴇɢᴀ ᴋʏᴀ ʀᴇ",
"ᴛᴜ ᴛᴏ ʀᴇᴀʟ ʀᴀɴᴅɪ ᴋɪ ᴀᴜʟᴀᴅ ʜᴀɪ sᴀʟʟʟʟʟʟᴇᴇᴇ",
"ʏʀ ᴛᴇʀɪ ʙᴀʜᴀɴɴɴɴɴɴ ᴋɪ ᴄʜᴜᴛᴛᴛᴛ ᴅᴇ ᴅᴇᴇᴇᴇᴇᴇ ɴᴀᴀᴀᴀ ʀᴇᴇᴇᴇᴇ",
"ᴛᴇʀɪ ʙᴀʜᴀɴɴɴɴɴɴ ᴋɪɪɪɪɪɪɪɪɪɪ ʟᴀʟʟʟʟʟʟ ʟᴀʟʟʟʟʟʟ ᴄʜᴜᴛᴛᴛᴛᴛᴛ",
"ᴛʜᴏᴍᴀsssss ᴋᴀᴀᴀᴀ ᴍᴏᴛᴛᴛᴀᴀᴀ ʟᴀɴᴅᴅᴅᴅ ʟᴇʟᴇ ᴀᴘɴɪ ʙᴀʜᴀɴɴɴ ᴋᴇᴇᴇᴇ ʟɪʏᴇᴇᴇᴇ",
]

SAPNA = [5959548791]

REPLYRAID = [
    "MADARCHOD",
    "BHOSDIKE",
    "LAAAWEEE KE BAAAAAL",
    "MAAAAR KI JHAAAAT KE BBBBBAAAAALLLLL",
    "MADRCHOD..",
    "TERI MA KI CHUT..",
    "LWDE KE BAAALLL.",
    "MACHAR KI JHAAT KE BAAALLLL",
    "TERI MA KI CHUT M DU TAPA TAP?",
    "TERI MA KA BHOSDAA",
    "TERI BHN SBSBE BDI RANDI.",
    "TERI MA OSSE BADI RANDDDDD",
    "TERA BAAP CHKAAAA",
    "KITNI CHODU TERI MA AB OR..",
    "TERI MA CHOD DI HM NE",
    "MIGHTY !!  BAAP BOLTE",
    "TERI MA KE STH REELS BNEGA ROAD PEE",
    "TERI MA KI CHUT EK DAM TOP SEXY",
    "MALUM NA PHR KESE LETA HU M TERI MA KI CHUT TAPA TAPPPPP",
    "LUND KE CHODE TU KEREGA TYPIN",
    "SPEED PKD LWDEEEE",
    "BAAP KI SPEED MTCH KRRR",
    "LWDEEE",
    "PAPA KI SPEED MTCH NHI HO RHI KYA",
    "ALE ALE MELA BCHAAAA",
    "[RYAN](t.me/PYTH0NXD) TERA BAAP !!",
    "CHUD GYA PAPA SEEE",
    "KISAN KO KHODNA OR",
    "SALE RAPEKL KRDKA TERA",
    "HAHAHAAAAA",
    "KIDSSSS",
    "BACHHE TERI MAA KI CHUTT",
    "TERI BHEN KI CHUTT BHOSDIWALE",
    "TERI MA CHUD GYI AB FRAR MT HONA",
    "YE LDNGE BAPP SE",
    "KIDSSS FRAR HAHAHH",
    "BHEN KE LWDE SHRM KR",
    "KITNI GLIYA PDWEGA APNI MA KO",
    "NALLEE",
    "SUAR KE PILLE TERI MAAKO SADAK PR LITAKE CHOD DUNGA 😂😆🤤",
    "ABE TERI MAAKA BHOSDA MADERCHOOD KR PILLE PAPA SE LADEGA TU 😼😂🤤",
    "GALI GALI NE SHOR HE TERI MAA RANDI CHOR HE 💋💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE PILLE KUTTE KE CHODE 😂👻🔥",
    "TERI MAAKO AISE CHODA AISE CHODA TERI MAAA BED PEHI MUTH DIA 💦💦💦💦",
    "TERI BEHEN KE BHOSDE ME AAAG LAGADIA MERA MOTA LUND DALKE 🔥🔥💦😆😆",
    "RANDIKE BACHHE TERI MAAKO CHODU CHAL NIKAL",
    "KITNA CHODU TERI RANDI MAAKI CHUTH ABB APNI BEHEN KO BHEJ 😆👻🤤",
    "TERI BEHEN KOTO CHOD CHODKE PURA FAAD DIA CHUTH ABB TERI GF KO BHEJ 😆💦🤤",
    "TERI GF KO ETNA CHODA BEHEN KE LODE TERI GF TO MERI RANDI BANGAYI ABB CHAL TERI MAAKO CHODTA FIRSE ♥️💦😆😆😆😆",
    "HARI HARI GHAAS ME JHOPDA TERI MAAKA BHOSDA 🤣🤣💋💦",
    "CHAL TERE BAAP KO BHEJ TERA BASKA NHI HE PAPA SE LADEGA TU",
    "TERI BEHEN KI CHUTH ME BOMB DALKE UDA DUNGA MAAKE LAWDE",
    "TERI MAAKO TRAIN ME LEJAKE TOP BED PE LITAKE CHOD DUNGA SUAR KE PILLE 🤣🤣💋💋",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI BEHEN KO CHOD CHODKE VIDEO BANAKE XNXX.COM PE NEELAM KARDUNGA KUTTE KE PILLE 💦💋",
    "TERI MAAAKI CHUDAI KO PORNHUB.COM PE UPLOAD KARDUNGA SUAR KE CHODE 🤣💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE BACHHE TEREKO CHAKKO SE PILWAVUNGA RANDIKE BACHHE 🤣🤣",
    "TERI MAAKI CHUTH FAADKE RAKDIA MAAKE LODE JAA ABB SILWALE 👄👄",
    "TERI BEHEN KI CHUTH ME MERA LUND KAALA",
    "TERI BEHEN LETI MERI LUND BADE MASTI SE TERI BEHEN KO MENE CHOD DALA BOHOT SASTE SE",
    "BETE TU BAAP SE LEGA PANGA TERI MAAA KO CHOD DUNGA KARKE NANGA 💦💋",
    "HAHAHAH MERE BETE AGLI BAAR APNI MAAKO LEKE AAYA MATH KAT OR MERE MOTE LUND SE CHUDWAYA MATH KAR",
    "CHAL BETA TUJHE MAAF KIA 🤣 ABB APNI GF KO BHEJ",
    "SHARAM KAR TERI BEHEN KA BHOSDA KITNA GAALIA SUNWAYEGA APNI MAAA BEHEN KE UPER",
    "ABE RANDIKE BACHHE AUKAT NHI HETO APNI RANDI MAAKO LEKE AAYA MATH KAR HAHAHAHA",
    "KIDZ MADARCHOD TERI MAAKO CHOD CHODKE TERR LIYE BHAI DEDIYA",
    "JUNGLE ME NACHTA HE MORE TERI MAAKI CHUDAI DEKKE SAB BOLTE ONCE MORE ONCE MORE 🤣🤣💦💋",
    "GALI GALI ME REHTA HE SAND TERI MAAKO CHOD DALA OR BANA DIA RAND 🤤🤣",
    "SAB BOLTE MUJHKO PAPA KYOUNKI MENE BANADIA TERI MAAKO PREGNENT 🤣🤣",
    "SUAR KE PILLE TERI MAAKI CHUTH ME SUAR KA LOUDA OR TERI BEHEN KI CHUTH ME MERA LODA",
    "CHAL CHAL APNI MAAKI CHUCHIYA DIKA",
    "HAHAHAHA BACHHE TERI MAAAKO CHOD DIA NANGA KARKE",
    "TERI GF HE BADI SEXY USKO PILAKE CHOODENGE PEPSI",
    "2 RUPAY KI PEPSI TERI MUMMY SABSE SEXY 💋💦",
    "TERI MAAKO CHEEMS SE CHUDWAVUNGA MADERCHOOD KE PILLE 💦🤣",
    "TERI BEHEN KI CHUTH ME MUTHKE FARAR HOJAVUNGA HUI HUI HUI",
    "SPEED LAAA TERI BEHEN CHODU RANDIKE PILLE 💋💦🤣",
    "ARE RE MERE BETE KYOUN SPEED PAKAD NA PAAA RAHA APNE BAAP KA HAHAH🤣🤣",
    "SUN SUN SUAR KE PILLE JHANTO KE SOUDAGAR APNI MUMMY KI NUDES BHEJ",
    "ABE SUN LODE TERI BEHEN KA BHOSDA FAAD DUNGA",
    "TERI MAAKO KHULE BAJAR ME CHOD DALA 🤣🤣💋",
    "SHRM KR",
    "MERE LUND KE BAAAAALLLLL",
    "KITNI GLIYA PDWYGA APNI MA BHEN KO",
    "RNDI KE LDKEEEEEEEEE",
    "KIDSSSSSSSSSSSS",
    "Apni gaand mein muthi daal",
    "Apni lund choos",
    "Apni ma ko ja choos",
    "Bhen ke laude",
    "Bhen ke takke",
    "Abla TERA KHAN DAN CHODNE KI BARIII",
    "BETE TERI MA SBSE BDI RAND",
    "LUND KE BAAAL JHAT KE PISSSUUUUUUU",
    "LUND PE LTKIT MAAALLLL KI BOND H TUUU",
    "KASH OS DIN MUTH MRKE SOJTA M TUN PAIDA NA HOTAA",
    "GLTI KRDI TUJW PAIDA KRKE",
    "SPEED PKDDD",
    "Gaand main LWDA DAL LE APNI MERAAA",
    "Gaand mein bambu DEDUNGAAAAAA",
    "GAND FTI KE BALKKK",
    "Gote kitne bhi bade ho, lund ke niche hi rehte hai",
    "Hazaar lund teri gaand main",
    "Jhaant ke pissu-",
    "TERI MA KI KALI CHUT",
    "Khotey ki aulad",
    "Kutte ka awlad",
    "Kutte ki jat",
    "Kutte ke tatte",
    "TETI MA KI.CHUT , tERI MA RNDIIIIIIIIIIIIIIIIIIII",
    "Lavde ke bal",
    "muh mei lele",
    "Lund Ke Pasine",
    "MERE LWDE KE BAAAAALLL",
    "HAHAHAAAAAA",
    "CHUD GYAAAAA",
    "Randi khanE KI ULADDD",
    "Sadi hui gaand",
    "Teri gaand main kute ka lund",
    "Teri maa ka bhosda",
    "Teri maa ki chut",
    "Tere gaand mein keede paday",
    "Ullu ke pathe",
    "SUNN MADERCHOD",
    "TERI MAA KA BHOSDA",
    "BEHEN K LUND",
    "TERI MAA KA CHUT KI CHTNIIII",
    "MERA LAWDA LELE TU AGAR CHAIYE TOH",
    "GAANDU",
    "CHUTIYA",
    "TERI MAA KI CHUT PE JCB CHADHAA DUNGA",
    "SAMJHAA LAWDE",
    "YA DU TERE GAAND ME TAPAA TAP��",
    "TERI BEHEN MERA ROZ LETI HAI",
    "TERI GF K SAATH MMS BANAA CHUKA HU���不�不",
    "TU CHUTIYA TERA KHANDAAN CHUTIYA",
    "AUR KITNA BOLU BEY MANN BHAR GAYA MERA�不",
    "TERIIIIII MAAAA KI CHUTTT ME ABCD LIKH DUNGA MAA KE LODE",
    "TERI MAA KO LEKAR MAI FARAR",
    "RANIDIII",
    "BACHEE",
    "CHODU",
    "RANDI",
    "RANDI KE PILLE",
    "TERIIIII MAAA KO BHEJJJ",
    "TERAA BAAAAP HU",
    "teri MAA KI CHUT ME HAAT DAALLKE BHAAG JAANUGA",
    "Teri maa KO SARAK PE LETAA DUNGA",
    "TERI MAA KO GB ROAD PE LEJAKE BECH DUNGA",
    "Teri maa KI CHUT MÉ KAALI MITCH",
    "TERI MAA SASTI RANDI HAI",
    "TERI MAA KI CHUT ME KABUTAR DAAL KE SOUP BANAUNGA MADARCHOD",
    "TERI MAAA RANDI HAI",
    "TERI MAAA KI CHUT ME DETOL DAAL DUNGA MADARCHOD",
    "TERI MAA KAAA BHOSDAA",
    "TERI MAA KI CHUT ME LAPTOP",
    "Teri maa RANDI HAI",
    "TERI MAA KO BISTAR PE LETAAKE CHODUNGA",
    "TERI MAA KO AMERICA GHUMAAUNGA MADARCHOD",
    "TERI MAA KI CHUT ME NAARIYAL PHOR DUNGA",
    "TERI MAA KE GAND ME DETOL DAAL DUNGA",
    "TERI MAAA KO HORLICKS PILAUNGA MADARCHOD",
    "TERI MAA KO SARAK PE LETAAA DUNGAAA",
    "TERI MAA KAA BHOSDA",
    "MERAAA LUND PAKAD LE MADARCHOD",
    "CHUP TERI MAA AKAA BHOSDAA",
    "TERIII MAA CHUF GEYII KYAAA LAWDEEE",
    "TERIII MAA KAA BJSODAAA",
    "MADARXHODDD",
    "TERIUUI MAAA KAA BHSODAAA",
    "TERIIIIII BEHENNNN KO CHODDDUUUU MADARXHODDDD",
    "NIKAL MADARCHOD",
    "RANDI KE BACHE",
    "TERA MAA MERI FAN",
    "TERI SEXY BAHEN KI CHUT OP"
]

GROUP = [-1001948563227]


PORMS = [
        "https://te.legra.ph/file/a66008b78909b431fc92b.mp4",
        "https://te.legra.ph/file/0ab82f535e1193d09c0e4.mp4",
        "https://te.legra.ph/file/1ab9cde9388117db9d26c.mp4",
        "https://te.legra.ph/file/75e49339469dbf9ad1dd2.mp4",
        "https://telegra.ph/file/9bcc076fd81dfe3feb291.mp4",
        "https://telegra.ph/file/b7a1a42429a65f64e67af.mp4",
        "https://telegra.ph/file/dc3da5a3eb77ae20fa21d.mp4",
        "https://telegra.ph/file/7b15fbca08ae1e73e559c.mp4",
        "https://telegra.ph/file/a9c1dea3f34925bb60686.mp4",
        "https://telegra.ph/file/913b4e567b7f435b7f0db.mp4",
        "https://telegra.ph/file/5a5d1a919a97af2314955.mp4",
        "https://telegra.ph/file/0f8b903669600d304cbe4.mp4",
        "https://telegra.ph/file/f3816b54c9eb7617356b6.mp4",
        "https://telegra.ph/file/516dbaa03fde1aaa70633.mp4",
        "https://telegra.ph/file/07bba6ead0f1e381b1bd1.mp4",
        "https://telegra.ph/file/0a4f7935df9b4ab8d62ed.mp4",
        "https://telegra.ph/file/40966bf68c0e4dbe18058.mp4",
        "https://telegra.ph/file/50637aa9c04d136687523.mp4",
        "https://telegra.ph/file/b81c0b0e491da73e64260.mp4",
        "https://telegra.ph/file/4ddf5f29783d92ae03804.mp4",
        "https://telegra.ph/file/4037dc2517b702cc208b1.mp4",
        "https://telegra.ph/file/33cebe2798c15d52a2547.mp4",
        "https://telegra.ph/file/4dc3c8b03616da516104a.mp4",
        "https://telegra.ph/file/6b148dace4d987fae8f3e.mp4",
        "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
        "https://telegra.ph/file/98d3eb94e6f00ed56ef91.mp4",
        "https://telegra.ph/file/1fb387cf99e057b62d75d.mp4",
        "https://telegra.ph/file/6e1161f63879c07a1f213.mp4",
        "https://telegra.ph/file/0bf4defb9540d2fa6d277.mp4",
        "https://telegra.ph/file/d5f8280754d9aa5dffa6a.mp4",
        "https://telegra.ph/file/0f23807ed1930704e2bef.jpg",
        "https://telegra.ph/file/c49280b8f1dcecaf86c00.jpg",
        "https://telegra.ph/file/f483400ff141de73767ca.jpg",
        "https://telegra.ph/file/1543bbea4e3c1abb6764a.jpg",
        "https://telegra.ph/file/a0d77be0d769c7cd334ab.jpg",
        "https://telegra.ph/file/6c6e93860527d2f577df8.jpg",
        "https://telegra.ph/file/d987b0e72eb3bb4801f01.jpg",
        "https://telegra.ph/file/b434999287d3580250960.jpg",
        "https://telegra.ph/file/0729cc082bf97347988f7.jpg",
        "https://telegra.ph/file/bb96d25df82178a2892e7.jpg",
        "https://telegra.ph/file/be73515791ea33be92a7d.jpg",
        "https://telegra.ph/file/fe234d6273093282d2dcc.jpg",
        "https://telegra.ph/file/66254bb72aa8094d38250.jpg",
        "https://telegra.ph/file/44bdaf37e5f7bdfc53ac6.jpg",
        "https://telegra.ph/file/e561ee1e1ca88db7e8038.jpg",
        "https://telegra.ph/file/f1960ccfc866b29ea5ad2.jpg",
        "https://telegra.ph/file/97622cad291472fb3c4aa.jpg",
        "https://telegra.ph/file/a46e316b413e9dc43e91b.jpg",
        "https://telegra.ph/file/497580fc3bddc21e0e162.jpg",
        "https://telegra.ph/file/3e86cc6cab06a6e2bde82.jpg",
        "https://telegra.ph/file/83140e2c57ddd95f310e6.jpg",
        "https://telegra.ph/file/2b20f8509d9437e94fed5.jpg",
        "https://telegra.ph/file/571960dcee4fce56698a4.jpg",
        "https://telegra.ph/file/25929a0b49452d8946c14.mp4",
        "https://telegra.ph/file/f5c9ceded3ee6e76a5931.jpg",
        "https://telegra.ph/file/a8bf6c6df8a48e4a306ca.jpg",
        "https://telegra.ph/file/af9e3f98da0bd937adf6e.jpg",
        "https://telegra.ph/file/2fcccbc72c57b6892d23a.jpg",
        "https://telegra.ph/file/843109296a90b8a6c5f68.jpg"
]


MRAID = [
    "Tere naalo challiye haseen koyi NA 😁😁",
    "Taare chann ambar zameen koyi nA",
    "Main Jado Tere Mode Utte Sir Rakheya🧐🧐",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😖😖",
    "Sohniyan Vi Laggan Giyan Fer Walian😍😍",
    "Galan Nal Jado Takraiyan Waliyan🥰🥰",
    "Tare Dekhi Labh Labh Kiven Harde😁😁",
    "Tu Bala Ch Lakoiyan Jado Ratan Kaliyan😒😒",
    "Main Sab Kuj Har Tere Utton De’unga😌😌",
    "Sab Kuj War Tere Utton De’unga😉😉",
    "Akhir Ch Jan Tainu De’un Apni😎😎",
    "Chala Tainu Bhavein Pehli War De’unga😚😚",
    "Han Main Cheti Cheti Lawan😫😫",
    "Tere Nal Laini an😣😣",
    "Samay Da Tan Bhora Vi Yakeen Koi Na🥺🥺",
    "Tere Nalo Jhaliye Haseen Koi Na🥰🥰",
    "Tare Chann Ambar Zameen Koi Na😘😘",
    "Tu Yar Mera Tu Hi Ae Sahara AdiyE",
    "Main Pani Tera Mera Tu Kinara Adiye",
    "Phul Ban Jai Main Khushboo Bann Ju",
    "Deevan Bani Mera Teri Lau Ban Ju",
    "Haye Ujadiyan Thawan Te Banate Bag Ne",
    "Teriyan Ankhan Ne Kitte Jadu Yad Ne",
    "Jado Wang Kolon Phadi Vi Ni KassKe",
    "Totte Sambh Rakhe Tutte Hoye Kach De",
    "Han Ki Dil Yadan Rakhda Ae, Sambh Sambh Ke",
    "Hor Dil Sajjna Machine Koi Na",
    "Tere Nalo Jhaliye Haseen Koi Na",
    "Tare Chann Ambar Zameen Koi Na",
    "Main Jado Tere Mode Utte Sir Rakheya",
    "Eh Ton Sachi Sama Vi Haseen Koi Na",
    "Kine Din Hogye Meri Akh Soi Na",
    "Tere Ton Bagair Mera Aithe Koi Na",
    "Tu Bhukh Vi Ae Tu Hi Ae Guzara Adiye",
    "Mannu Sab Kari Tu Ishara Adiye",
    "Ho Khaure Kinni War Seene Vich Khubiyan",
    "Surme De Vich Dovein Ankhan Dubbiyan",
    "Kini Sohni Lagge Jadon Chup Kar Je",
    "Jandi Jandi Shaman Nu Vi Dhup Kar Je",
    "Haye Main Paun Farmaishi Rang Tere Sohniye",
    "Unj Bahotan Gifty Shaukeen Koi Na",
    "Tare Chann Ambar Zameen Koi Na🥰🥰",
    "Tere Nalo Jhaliye Haseen Koi Na😍😍",
    "Main Jado Tere Mode Utte Sir Rakheya😁😁",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😒😒",
    "Kanna Wich Jhumka👀👀",
    "Akhan Wich Surma🙈🙈",
    "Ho Jaise Strawberry Candy😋😋",
    "Nakk Utte Koka🤨🤨",
    "Jeena Kare Aukha🤭🤭",
    "Haye Meri Jaan Kadd Laindi😌😌",
    "Tere Nakhre Haye Tauba Sanu Maarde🤫🤫",
    "Ho Gaya Hai Mera Baby Bura HaaL😊😊",
    "Sachi Lut Gaye Hum Tere Is Pyar Mein😏😏",
    "Jeeni Zindagi Hai Bas Tere Naal😚😚",
    "I Love YoU SO MUCH 😍😍",
    "cause I Love You 😘😘",
    "Sapno Mein Mere AayI😝😝",
    "Baby! Lage Sohna Kitna PyarA😚😚",
    "Sapno Mein Mere Aayi😝😝",
    "Uff Oh Phir Neendein Hi Churayi😜😜",
    "Oh No! Tera Husan Nazara🥰🥰",
    "Tainu Diamond Mundri Pehnawa😎😎",
    "Naale Duniya Sari Ghumawa🙈🙈",
    "Chhoti-Chhoti Gallan Utte Main Hasavaan💙💙",
    "Yaara Kade Vi Na Tainu Main Rulawaan🙊🙊",
    "cause I Love You  🙈🙈",
    "I Love You ❤️❤️",
    "cause I Love You🙈🙈",
    "Yaari Laawan Sachi YaarI💫💫",
    "Tu Jaan Ton Vi Pyari😁😁",
    "Will Love You To The Moon And Back😆😆",
    "Hogi Saza Na Koyi Hogi😙😙",
    "Chahe Karun Chori Chaand Taare😉😉",
    "Imma Give You Them😅😅",
    "Yaari Laavan Sachi YaarI😘😘",
    "Tu Jaan Ton Vi PyarI😆😆",
    "Will Love You To The Moon And Back💕💕",
    "Hogee Sazaa Na Koyi Hogi💓💓",
    "Chahe Karun Chori Chaand Taare🥺🥺",
    "Imma Give You Them🥵🥵",
    "Puri Karunga Main Teri Sari Khahishein😁😁",
    "Tera Rakhanga Main Rajj Ke Khayal😘😘",
    "Kitni Khoobiyan Hai Tere Is Yaar Mein🥰🥰",
    "Aaja Bahon Mein Tu Bahein Bas Daal😂😂",
    "Aur Hota Nahi Ab Intezar🤩🤩",
    "Aur Hota Nahee Ab Intezaar😘😘",
    "cause I Love You 😍😍",
    "I Love YoU 😙😙",
    "cause I Love You",
    "I Love YoU SOOOOOOOOOOOOOOOOOO MUCHHHHHHHHHHHHHHHHHHHHH 😘😘",
    "WILL U BE MINE FOREVER??🤔🤔",
    "Je tu akh te main aan kaajal ve😌😌",
    "Tu baarish te main baadal ve🤫🤫",
    "Tu deewana main aan paagal ve🤪🤪",
    "Sohneya sohneya☺️☺️",
    "Je tu chann te main aan taara ve🤗🤗",
    "Main lehar te tu kinara ve😶😶",
    "Main aadha te tu saara ve🤗🤗",
    "Sohneya sohneya😗😗",
    "Tu jahan hai main wahan😘😘",
    "Tere bin main hoon hi kya🥲🥲",
    "Tere bin chehre se mere🤔🤔",
    "Udd jaaye rang ve😅😅",
    "Tujhko paane ke liye huM😁😁",
    "Roz mangein mannat ve🙈🙈",
    "Duniya to kya cheez hai yaara🙉🙉",
    "Tujhko paane ke liye hum😌😌",
    "Roz mangein mannat ve🤫🤫",
    "Duniya to kya cheez hai yaara🤔🤔",
    "Na parwah mainu apni aa😁😁",
    "Na parwah mainu duniya di👅👅",
    "Na parwah mainu apni aa😅😅",
    "Tere ton juda nahi kar sakdi🤬🤬",
    "Koyi taakat mainu duniya di😈😈",
    "Dooron aa jaave teri khushbu😎😎",
    "Akhan hun band taan vi vekh lawan😍😍",
    "Teri gali vich mera auna har roz😋😋",
    "Tera ghar jadon aave matha tek lawan😌😌",
    "Nirmaan tujhko dekh ke😏😏",
    "Aa jaave himmat ve😉😉",
    "Tujhko paane ke liye hum😊😊",
    "Roz mangein mannat ve😉😉",
    "Duniya to kya cheez hai yaara😌😌",
    "Thukra denge jannat ve😍😍",
    "Tujhko paane ke liye hum🤫🤫",
    "Roz mangein mannat ve😁😁",
    "Duniya to kya cheez hai yaara😏😏",
    "Thukra denge jannat ve😌😌",
    "SO MISS 😶😶",
    "KYA SOCHA APNE BAARE MAIN😆😆",
    "BADI MUSHKIL SE YEH SAB KARA H RE🥵🥵",
    "PAHLE PURA BOT HI KANG MAAR DIYA BUT🤫🤫",
    "WAHI ERROR AAYE JO AATE THE🥲🥲",
    "BUT TUMHARA HO CHUKA WALA BF😎😎",
    "AND FUTURE HUSBAND JO BANNE WALA THA WO BHOT SMART H RE😌😌",
    "ISS BAAR BOT BANAYA AND CHOTA SA EDIT KARA BAS😁😁",
    "AUR DEKO ABHI TUM USSI BOT SE YEH PADH PAA RHI😂😂",
    "HEHE BTW YEH CHORO MEKO NA TUMSE😶😶",
    "KUCH PUCHNA THA KI ME🤔🤔",
    "TUMHARE KABIL HU YA",
    "TUMHARE KABIL NHI😂💓",
    "AND EK AUR BAAT BOLNI THI KI😙😙",
    "I REALLY REALLY DEEPLY😙😙",
    "LOVE YOU FROM MY HEART TO YOUR HEAT AND MY SOUL ATTACHED BY YOUR SOUL CAN YOU BE MINE FOREVER😌😌❤️"
]


SRAID = [
    "इश्क़ है या कुछ और ये पता नहीं, पर जो तुमसे है किसी और से नहीं 😁😁",
    "मै कैसे कहू की उसका साथ कैसा है, वो एक शख्स पुरे कायनात जैसा है ",
    " तेरा होना ही मेरे लिये खास है, तू दूर ही सही मगर मेरे दिल के पास है ",
    "मुझे तेरा साथ ज़िन्दगी भर नहीं चाहिये, बल्कि जब तक तू साथ है तबतक ज़िन्दगी चाहिए 😖😖",
    "तुझसे मोहब्बत कुछ अलग सी है मेरी, तुझे खयालो में नहीं दुआओ में याद करते है😍😍",
    "तू हज़ार बार भी रूठे तो मना लूँगा तुझे",
    "मगर देख मोहब्बत में शामिल कोई दूसरा ना हो😁😁",
    "किस्मत यह मेरा इम्तेहान ले रही है😒😒",
    "तड़प कर यह मुझे दर्द दे रही है😌😌",
    "दिल से कभी भी मैंने उसे दूर नहीं किया😉😉",
    "फिर क्यों बेवफाई का वह इलज़ाम दे रही है😎😎",
    "मरे तो लाखों होंगे तुझ पर😚😚",
    "मैं तो तेरे साथ जीना चाहता हूँ😫😫",
    "वापस लौट आया है हवाओं का रुख मोड़ने वाला😣😣",
    "दिल में फिर उतर रहा है दिल तोड़ने वाला🥺🥺",
    "अपनों के बीच बेगाने हो गए हैं🥰🥰",
    "प्यार के लम्हे अनजाने हो गए हैं😘😘",
    "जहाँ पर फूल खिलते थे कभी😍😍",
    "आज वहां पर वीरान हो गए हैं🥰🥰",
    "जो शख्स तेरे तसव्वुर से हे महक जाये😁😁",
    "सोचो तुम्हारे दीदार में उसका क्या होगा😒😒",
    "मोहब्बत का एहसास तो हम दोनों को हुआ था",
    "फर्क सिर्फ इतना था की उसने किया था और मुझे हुआ था",
    "सांसों की डोर छूटती जा रही है",
    "किस्मत भी हमे दर्द देती जा रही है",
    "मौत की तरफ हैं कदम हमारे",
    "मोहब्बत भी हम से छूटती जा रही है",
    "समझता ही नहीं वो मेरे अलफ़ाज़ की गहराई",
    "मैंने हर लफ्ज़ कह दिया जिसे मोहब्बत कहते है",
    "समंदर न सही पर एक नदी तो होनी चाहिए",
    "तेरे शहर में ज़िन्दगी कही तो होनी चाहिए",
    "नज़रों से देखो तोह आबाद हम हैं",
    "दिल से देखो तोह बर्बाद हम हैं",
    "जीवन का हर लम्हा दर्द से भर गया",
    "फिर कैसे कह दें आज़ाद हम हैं",
    "मुझे नहीं मालूम वो पहली बार कब अच्छा लगा",
    "मगर उसके बाद कभी बुरा भी नहीं",
    "सच्ची मोहब्बत कभी खत्म नहीं होती",
    "वक़्त के साथ खामोश हो जाती है",
    "ज़िन्दगी के सफ़र में आपका सहारा चाहिए",
    "आपके चरणों का बस आसरा चाहिए",
    "हर मुश्किलों का हँसते हुए सामना करेंगे",
    "बस ठाकुर जी आपका एक इशारा चाहिए",
    "जिस दिल में बसा था नाम तेरा हमने वो तोड़ दिया",
    "न होने दिया तुझे बदनाम बस तेरे नाम लेना छोड़ दिया",
    "प्यार वो नहीं जो हासिल करने के लिए कुछ भी करव दे",
    "प्यार वो है जो उसकी खुशी के लिए अपने अरमान चोर दे",
    "आशिक के नाम से सभी जानते हैं😍😍",
    "इतना बदनाम हो गए हम मयखाने में🥰🥰",
    "जब भी तेरी याद आती है बेदर्द मुझे😍😍",
    "तोह पीते हैं हम दर्द पैमाने में🥰🥰",
    "हम इश्क़ के वो मुकाम पर खड़े है😁😁",
    "जहाँ दिल किसी और को चाहे तो गुन्हा लगता है😒😒",
    "सच्चे प्यार वालों को हमेशा लोग गलत ही समझते है👀👀",
    "जबकि टाइम पास वालो से लोग खुश रहते है आज कल🙈🙈",
    "गिलास पर गिलास बहुत टूट रहे हैं😋😋",
    "खुसी के प्याले दर्द से भर रहे हैं🤨🤨",
    "मशालों की तरह दिल जल रहे हैं🤭🤭",
    "जैसे ज़िन्दगी में बदकिस्मती से मिल रहे हैं😌😌",
    "सिर्फ वक़्त गुजरना हो तो किसी और को अपना बना लेना🤫🤫",
    "हम दोस्ती भी करते है तो प्यार की तरह😊😊",
    "जरूरी नहीं इश्क़ में बनहूँ के सहारे ही मिले😏😏",
    "किसी को जी भर के महसूस करना भी मोहब्बत है😚😚",
    "नशे में भी तेरा नाम लब पर आता है😘😘",
    "चलते हुए मेरे पाँव लड़खड़ाते हैं😍😍",
    "दर्द सा दिल में उठता है मेरे😘😘",
    "हसीं चेहरे पर भी दाग नजर आता है😍😍",
    "हमने भी एक ऐसे शख्स को चाहा😝😝",
    "जिसको भुला न सके और वो किस्मत मैं भी नहीं😜😜",
    "सच्चा प्यार किसी भूत की तरह होता है🥰🥰",
    "बातें तो सब करते है देखा किसी ने नहीं😚😚",
    "मत पूछ ये की मैं तुझे भुला नहीं सकता😝😝",
    "तेरी यादों के पन्ने को मैं जला नहीं सकता😜😜",
    "संघर्ष यह है कि खुद को मारना होगा🥰🥰",
    "और अपने सुकून की खातिर तुझे रुला नहीं सकता😚😚",
    "दुनिया को आग लगाने की ज़रूरत नहीं😎😎",
    "Naale Duniya Sari Ghumawa🙈🙈",
    "तो मेरे साथ चसल आग खुद लग जाएगी💙💙",
    "तरस गये है हम तेरे मुंह से कुछ सुनने को हम🙊🙊",
    "प्यार की बात न सही कोई शिकायत ही कर दे  🙈🙈",
    "तुम नहीं हो पास मगर तन्हाँ रात वही है ❤️❤️",
    "वही है चाहत यादों की बरसात वही है🙈🙈",
    "हर खुशी भी दूर है मेरे आशियाने से ❤️❤️",
    "खामोश लम्हों में दर्द-ए-हालात वही है💫💫",
    "करने लगे जब शिकवा उससे उसकी बेवफाई का😁😁",
    "रख कर होंट को होंट से खामोश कर दिया😆😆",
    "राह में मिले थे हम, राहें नसीब बन गईं😙😙",
    "ना तू अपने घर गया, ना हम अपने घर गये😉😉",
    "तुम्हें नींद नहीं आती तो कोई और वजह होगी😅😅",
    "अब हर ऐब के लिए कसूरवार इश्क तो नहीं😘😘",
    "अना कहती है इल्तेजा क्या करनी😆😆",
    "वो मोहब्बत ही क्या जो मिन्नतों से मिले💕💕",
    "न जाहिर हुई तुमसे और न ही बयान हुई हमसे💓💓",
    "बस सुलझी हुई आँखो में उलझी रही मोहब्बत🥺🥺",
    "गुफ्तगू बंद न हो बात से बात चले🥵🥵",
    "नजरों में रहो कैद दिल से दिल मिले😁😁",
    "है इश्क़ की मंज़िल में हाल कि जैसे😘😘",
    "लुट जाए कहीं राह में सामान किसी का🥰",
    "मुकम्मल ना सही अधूरा ही रहने दो😂😂",
    "ये इश्क़ है कोई मक़सद तो नहीं है🤩🤩",
    "वजह नफरतों की तलाशी जाती है😘😘",
    "मोहब्बत तो बिन वजह ही हो जाती है 😍😍",
    "सिर्फ मरी हुई मछली को ही पानी का बहाव चलाती है 😙😙",
    "जिस मछली में जान होती है वो अपना रास्ता खुद तय करती है",
    "कामयाब लोगों के चेहरों पर दो चीजें होती है 😘😘",
    "एक साइलेंस और दूसरा स्माइल🤔🤔",
    "मेरी चाहत देखनी है तो मेरे दिल पर अपना दिल रखकर देखe😌😌",
    "तेरी धड़कन ना भड्जाये तो मेरी मोहब्बत ठुकरा देना🤫🤫",
    "गलतफहमी की गुंजाईश नहीं सच्ची मोहब्बत में🤪🤪",
    "जहाँ किरदार हल्का हो कहानी डूब जाती है☺️☺️",
    "होने दो मुख़ातिब मुझे आज इन होंटो से अब्बास🤗🤗",
    "बात न तो ये समझ रहे है पर गुफ़्तगू जारी है😶😶",
    "उदासियाँ इश्क़ की पहचान है🤗🤗",
    "मुस्कुरा दिए तो इश्क़ बुरा मान जायेगा😗😗",
    "कुछ इस अदा से हाल सुनाना हमारे दिल😘😘",
    "वो खुद ही कह दे किदी भूल जाना बुरी बात है🥲",
    "माना की उससे बिछड़कर हम उमर भर रोते रहे🤔🤔",
    "पर मेरे मार जाने के बाद उमर भर रोएगा वो😅😅",
    "दिल में तुम्हारी अपनी कभी चोर जायेंगे😁😁",
    "आँखों में इंतज़ार की लकीर छोड़ जायेंगे🙈🙈",
    "किसी मासूम लम्हे मैं किसी मासूम चेहरे से🙉🙉",
    "मोहब्बत की नहीं जाती मोहब्बत हो जाती है😌😌",
    "करीब आओ तो शायद हम समझ लोगे😌😌",
    "ये दूरिया तो केवल फसले बढ़ती है🤫🤫",
    "तेरे इश्क़ में इस तरह मैं नीलाम हो जाओ🤔🤔",
    "आखरी हो मेरी बोली और मैं तेरे नाम हो जाऊ😌😌",
    "आप जब तक रहेंगे आंखों में नजारा बनकर😁😁",
    "रोज आएंगे मेरी दुनिया में उजाला बनकर👅👅",
    "उसे जब से बेवफाई की है मैं प्यार की राह में चल ना सका😅😅",
    "उसे तो किसी और का हाथ थाम लियाबस फिर कभी सम्भल नहीं सका👅👅",
    "एक ही ख़्वाब देखा है कई बार मैंने🤬🤬",
    "तेरी शादी में उलझी है चाहिए मेरे घर की😈😈",
    "तुम्हे मेरी मोहब्बत की कसम सच बताना😎😎",
    "गले में डाल कर बाहें किससे सीखाया है😍😍",
    "नहीं पता की वो कभी मेरी थी भी या नहीं😋😋",
    "मुझे ये पता है बस की माई तो था उमर बस उसी का रहा😌😌",
    "तुमने देखा कभी चाँद से पानी गिरते हुएe😏😏",
    "मैंने देखा ये मंज़र तू में चेहरा धोते हुए😉😉",
    "ठुकरा दे कोई चाहत को तू हस के सह लेना😊😊",
    "प्यार की तबियत में ज़बर जस्ती नहीं होती😉😉",
    "तेरा पता नहीं पर मेरा दिल कभी तैयार नहीं होगा😌😌",
    "मुझे तेरे अलावा कभी किसी और से प्यार नहीं होगा😍😍",
    "दिल में आहट सी हुई रूह में दस्तक गूँजी🤫🤫",
    "किस की खुशबू ये मुझे मेरे सिरहाने आई😁😁",
    "उम्र भर लिखते रहे फिर भी वारक सदा रहा😏😏",
    "जाने किया लफ्ज़ थे जो हम लिख नहीं पाये😌😌",
    "लगा के फूल हाथों से उसने कहा चुपके से😶😶",
    "अगर यहाँ कोई नहीं होता तो फूल की जगह तुम होते😆😆",
    "जान जब प्यारी थी मरने का शौक था🥵🥵",
    "अब मरने का शौक है तो कातिल नहीं मिल रहा🤫🤫",
    "सिर्फ याद बनकर न रह जाये प्यार मेरा🥲🥲",
    "कभी कभी कुछ वक़्त के लिए आया करो😎😎",
    "मुझ को समझाया ना करो अब तो हो चुकी हूँ मुझ मैं😌😌",
    "मोहब्बत मशवरा होती तो तुम से पूछ लेता😁😁",
    "उन्हों ने कहा बहुत बोलते हो अब क्या बरस जाओगे😂😂",
    "हमने कहा जिस दिन चुप हो गया तुम तरस जाओ गए😶😶",
    "कुछ ऐसे हस्दे ज़िन्दगी मैं होते है🤔🤔",
    "के इंसान तो बच जाता है मगर ज़िंदा नहीं रहता😂💓"
]


CRAID = [
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
    'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
    'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
    'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
    'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
    'NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN',
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
    'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR',
    'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU',
    'VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
    'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ'
]
